### ISSUE TITLE
iOS: setting main view to Focus also affects Shared view

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#1014]
If you set your main view to Focus in the iOS app (iPhone or iPad), then tap the NewsBlur logo to look at you're shared stories, you will only see the shared stores that match the Focus.  This could be construed as a feature, except that you have no way to change to the All mode without leaving the Share mode first.

I commonly use the Shared view as a way to store stories to show my wife when she gets home from work (I use the Saved section for stories I want to look at later), which is why I noticed this -- I'm in the Shared view every day.

This occurs with the latest NewsBlur beta (7.0.0 (75))

**Comment by samuelclay** [comment]
There's some confusion between All/Unread/Focus and All Stories/Unread Stories. If you're in a feed under Focus, the All/Unread refers to All Focus Stories and All Unread Focus Stories. In other words, that's intentional. You cannot change intelligence filters inside the feed on iOS. You can on the web, but it's simpler this way.
