### ISSUE TITLE
Unsubscribe: confusing message

### ISSUE THREAD

**Issue by blshkv** [samuelclay/NewsBlur#1021]
Hi, this bug is about a web application.

The current "unsubscribe" message is really confusing. Users need to choose "DELETE THIS SITE". And then, click on "REALLY DELETE?".

Please rename to the proper "Unsubscribe" title. Also, the UPPERCASE message should be used only for REALLY important and CRITICAL messages. You SHOULD NOT use them everywhere because it meant to be a SCREAM!

**Comment by samuelclay** [comment]
Hah, I remember making it "Delete this site" instead of "Unsubscribe" from the very first day. I remember thinking how weird it was that NetNewsWire and Google Read used the unsubscribe nomenclature when what you wanted was to delete the site. That's been there since day one and one of the reasons I built my own news reader was for decisions like this one. I think unsubscribe is obtuse and reveals more of the mechanism of the news reader than most users care for.

As for the design, that's also sticking around. I may choose to opt for a redesign, but with user attribution being what it is, I'm not convinced it'll be worth the investment.

**Comment by blshkv** [comment]
Well, it's your call. Buy I feel like if i click on that big red BUTTON, the site will be really deleted. So i have to remind myself that this is not an admin interface, and the site will still around. 

Perhaps, you can consider renaming it to "delete this rss feed". That would make more sense from both users and reader prospective

**Comment by samuelclay** [comment]
I tend to not use RSS anywhere, as I think feeds and RSS are also obtuse. Site is a word that's been pretty agreeable thus far.

**Comment by blshkv** [comment]
I will leave with you to find a better word. "delete site" is not correct and confusing.
