### ISSUE TITLE
iOS: iOS folders do not render correctly if there are dashes in your folder names

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1043]
See https://getsatisfaction.com/newsblur/topics/only-displays-a-few-folders-to-move-feeds-to-in-ios.

If a subfolder is "x - y" it seems to render only as "y"; some combinations of dashes will cause a folder not to render at all.  This is likely related to the use of dashes to separate subfolders in lists (flatten_folders) which is inherently ambiguous.

**Comment by samuelclay** [comment]
Thought about this for months but I'm going to have to say that this is just a known issue.

**Comment by Dejal** [comment]
I was just thinking about this one. A solution could be to have the server use some less common sequence for the folder separator, e.g. `{|}` or similar. And on the client side, it could display that as `▸`. Of course, changing the server response is problematic, so that'd be a non-starter.

A better option could be to have the server escape a literal ` - ` in the folder name, e.g. like `x \- y`. Or replace a ` - ` with an en-dash variation, e.g. `x – y`.  That could be done without a breaking change of the server response.

The client could automatically replace a ` - ` (space hyphen space) with a ` – ` (space en-dash space) or other variation when the user adds or renames a folder.

**Comment by samuelclay** [comment]
It's brittle code I believe, although that shouldn't be a reason not to touch it. It's just that screwing up anything here causes all sorts of bad behavior in terms of duplicated folders. I would be happy to change it to a special delimiter but I worry that's it's going to cause issues. Anywhere there is `parent_folder`, such as deleting feeds (in folders, so only the one feeds gets deleted), moving feeds, renaming folders, adding feeds, and loading feeds, will need to be inspected.

**Comment by Dejal** [comment]
Yeah, I don't think it's feasible to change the folder separator, as that'd not only possibly have wide-ranging effects on the server, but would break older versions of the clients.

But escaping non-delimiter use of a dash within a folder name shouldn't break anything. Older clients would just display the escaped form, and it'd be easy enough to update to support displaying without the escape character, and to escape usage of a dash when sending to the server.

Not super important, and can wait till you have time, though I imagine people occasionally encounter issues with this.

**Comment by samuelclay** [comment]
#1322 will handle this by moving away from folder names and towards a prefixed uuid table that finally does away with folder names being special.
