### ISSUE TITLE
Android: New preference for OLED friendly dark theme

### ISSUE THREAD

**Issue by emash** [samuelclay/NewsBlur#1057]
Would like to see completly black background when dark theme is enabled.

**Comment by samuelclay** [comment]
Let's make this a toggle preference in the theme settings.

**Comment by dosiecki** [comment]
This comes up in pretty much every app that gets this request: how little brightness is enough?

OLED power consumption is a linear function of average pixel brightness (the V in HSV).  The default theme has V̅=90% for most screens.  The current dark theme lowers that to about V̅=10% for the feed list and V̅=12% for the story list.  The story itself, of course, largely depends on the content.

A very rough mock shows that dropping the backgrounds to an eye-searing black only get us down by about an additional -4% V̅.  In order to go lower, we'll also need to drop the V for text and borders.  Every component we flatten to black impacts readability, though.  What is our target brightness reduction to consider this worth implementing?

**Comment by emash** [comment]
It is consistent with the rest of most android distributions' oled themes. And it looks cool also.

**Comment by samuelclay** [comment]
I would just set the background to 100% black, leaving the rest of the UI just as it is for the dark theme.

**Comment by dosiecki** [comment]
Implemented a very basic 'black' theme with all black backgrounds and greatly darkened gradients and borders.  Got the whole-screen V̅ (on my phone, at least) down from 9% to 5% for the feed list and from 10% to 4% for the story list (for a sample feed with a fairly neutral color set).  Story detail view is, of course, highly dependent on story content, but I suspect a similar reduction factor there for stories that aren't solid images.

**Comment by dosiecki** [comment]
implemented in #1071
