### ISSUE TITLE
Android: Immersive Mode is not supported on Amazon devices

### ISSUE THREAD

**Issue by LiliWeiSE** [samuelclay/NewsBlur#1084]
Hi,

When reading the news, NewsBlur enters immersive mode and interacting with the app will not show the navigation bar. However, on amazon devices this is not supported. Any interaction with the app will bring the navigation bar and status bar back. So the full screen mode is not usable.

I found a reference discussion on Amazon developer forum:
https://forums.developer.amazon.com/questions/14224/immersive-mode.html

**Comment by dosiecki** [comment]
Just to clarify - are you using the fullscreen button that is available while reading a story, or is the app going fullscreen/immersive in other places or without consent?

Once fullscreen/immersive, it is by design that we respect when the system kicks us out of that mode.  We also leave fullscreen if you do tap inside blank/unused parts of the story, per the recommendation of the Android docs.

If a device fails to respect our request to go into fullscreen/immersive mode, there isn't a whole lot we can do about it.  Unfortunately, the linked recommendation by the AMZN team goes against the Android recommendations, and in order to support the most devices, we generally follow the latter.  (to get pedantic, `LayoutParams.FLAG_FULLSCREEN` is for apps that go fullscreen and stay that way, not for ones like ours that generally run like a normal app except when you are expressly reading a feed in fullscreen/immersive mode.  if we followed that suggestion, the system gesture to escape fullscreen mode would fail on some devices, potentially trapping people in the app story view.)

**Comment by frankFic** [comment]
Yes, I meant the full screen button on the action bar. On amazon device, even I just scroll the post, the full screen mode exits.

Thanks for your detailed explanation. Maybe I just do not use full screen mode.

**Comment by dosiecki** [comment]
Yeah, having done some more research, it looks like various AMZN devices do some uniquely wacky things when they go fullscreen/immersive.  Without adding device-specific workarounds, our hands might be tied, and for those we'd need to get our hands on the hardware.

If any of the other devs have a Fire device, we might be able to detect AMZN devices and play with using a subset of our current combination of `VIEW.SYSTEM_UI_FLAG_*` flags that doesn't include the auto-escaping flags.  That would at least let some subset of the action bar / navigation bar / and status bar get hidden until the activity is paused.

**Comment by sictiru** [comment]
https://github.com/samuelclay/NewsBlur/issues/1392
