### ISSUE TITLE
Self-hosting: Is it possible to install locally without email registration/verification?

### ISSUE THREAD

**Issue by myoriginalusername** [samuelclay/NewsBlur#1114]
As it stands, when self hosting/installing locally, as part of the user account creation/registration process, Newsblur will try to email you on the email address you enter on signup.

Is it possible to register/create an account without the need to hook up Newsblur to a mail server to send emails to new users (when the new user will just be me anyway)?

Right now, with no mail server set up, when trying to sign up, I will hit an error like this:

> NoAnswer at /reader/signup
> The DNS response does not contain an answer to the question: example.com. IN MX

_(where example.com is the bogus email domain I use to create my account)._

**Comment by samuelclay** [comment]
Seems you're hitting my spam detection. I run a DNS check on domain of email to sanity check. I have a branch that's ready to merge that moves to Google's recaptcha, but I haven't merged it for some reason. Probably because it's a big dependency right in the middle of my signup workflow that could go wrong some day and is hard to test.

**Comment by samuelclay** [comment]
Try adding this to your local_settings.py:

    AUTO_ENABLE_NEW_USERS = True

That way you don't need the email to be sent and the user will just work. Alternatively, if that doesn't work, just comment out the DNS check in `apps/reader/forms.py` around the line `if not query(domain, 'MX'):`
