### ISSUE TITLE
running newsblur in docker behind a proxy 

### ISSUE THREAD

**Issue by gruzilla** [samuelclay/NewsBlur#1176]
hey, first thank you very much for newsblur! i use it on a daily basis :)

my problem:

i try to run newsblur on my server behind a proxy.
unfortunately the default profile picture is loaded from https://localhost/media... and additionally i am having only limited experience with django

what i have tried so far:

i have configured my proxy to send the X-Forwarded-Host header.
i additionally added the following to my local_settings.py and rebuild the docker-image:

```
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```

did i miss something?

**Comment by samuelclay** [comment]
Hi, I'm glad you're a regular user but I'm afraid I can't debug this without more information on what's missing. Also, the docker support is unofficial and as far as I know, a bit broken right now. You'll have to install from source, which can be tricky without django experience.

**Comment by ttimasdf** [comment]
You need to fix the Docker image manually. @gruzilla

1. Fake an virtualenv folder inside project root. Otherwise Django Admin assets will not show correctly.
```
cd <where_ever_you_clone_this_project>
mkdir -p venv && ln -sf /usr/local venv/newsblur
# docker build or docker-compose build as you prefer
```

2. Edit Site settings at http://localhost:8000/admin/sites/site/1/
There's a field with value `localhost`, edit the value to suit your need, in your case it should be maybe `localhost:8000`.

**Comment by samuelclay** [comment]
I'm working on getting better Docker support and a one-line install process working. Follow #1316 for updates.
