### ISSUE TITLE
Android: Emailing stories should include story title in subject

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1198]
Like the title says.

**Comment by samuelclay** [comment]
Didn't seem to take for me. Still seeing an empty subject line. I'm using the Gmail share action.

**Comment by samuelclay** [comment]
Also, can we include the story content (and if available, use the story full text instead)?

**Comment by caleb-allen** [comment]
Is this when you hit `Share this story`, or if you click `Send story to...`

![Screenshot_1562012728](https://user-images.githubusercontent.com/3279748/60464574-36890200-9c0c-11e9-9f53-63c4682e9e9e.png)

The copy and functionality of those menu items may be a behavior we'd want to change. But can you confirm that it is when you click `Send story to...` that you're continuing to see the problem?

**Comment by samuelclay** [comment]
Send story to.

**Comment by caleb-allen** [comment]
What Android version are you on?

**Comment by caleb-allen** [comment]
![Screenshot_1562020150](https://user-images.githubusercontent.com/3279748/60470351-6987c180-9c1d-11e9-9ae6-c6f0c53b891c.png)
I'm trying to recreate it

**Comment by caleb-allen** [comment]
@samuelclay could you try again with this PR included?

**Comment by samuelclay** [comment]
It looks like this now
![Screenshot_20190806-123924](https://user-images.githubusercontent.com/44229/62558554-262cfe00-b82e-11e9-9a49-af3cc1043fa1.png)

**Comment by samuelclay** [comment]
It should look like this.

![2019-08-06 09 40 26](https://user-images.githubusercontent.com/44229/62558615-478dea00-b82e-11e9-8855-960fb375f2ff.png)

**Comment by samuelclay** [comment]
Can you include the `original_text` if it exists (and is downloaded, and as the Text view is defaulted per-feed, it's likely to be downloaded), otherwise the `story_content`, and link the story title to the `story_permalink`.

**Comment by sictiru** [comment]
After testing various combinations and ways of creating the email intent, a compromise had to be made.
The `original_text` is included if available, with a fallback to `story_content`. The story title is shown in the native "share chooser" instead of the link. The chooser could render HTML code but in that case the copy function/button won't work. 
Once in the email client, Gmail in this case, it can't build a hyperlink from HTML so the next best thing was to include `title`, followed by the `story_permalink` which will be displayed as a hyperlink once the email is received.
