### ISSUE TITLE
iOS: Returning to app shows "unable to mark unread" popup

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1223]
From user feedback (and something I've also personally experienced many times):

open feed
open a story 
turn off display with power button
swipe up, unlock device with face id
news blur opens at story with error “Failed to unread story”
iOS 12.4, iPhone XS Max, most recent app. has been happening for a while now.

**Comment by Dejal** [comment]
This issue was due to iOS 12 and later being more strict about performing network operations when the app is in the background. It was most noticeable here because this occurred when preparing for state restoration while suspending the app. But it could occur with any network request, if the phone is locked or the app suspended while underway. So to fix this and other requests, I have wrapped the network requests with the background task mechanism, so they can gracefully complete uninterrupted.

I also added methods to provide a simpler way to do network requests in the common usage of calling success and failure methods instead of blocks.

**Comment by samuelclay** [comment]
Excellent, that's good to know. I might release this as v9.1 then since it touches so many pieces.

**Comment by Dejal** [comment]
I'll be doing more NewsBlur changes over the next few days, if you want to wait and include them too.

**Comment by samuelclay** [comment]
Ok, I'll aim for early September then.
