### ISSUE TITLE
iOS: Statistics dialog

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1238]
I'm surprised it's taken this long to realize we don't have the Statistics dialog in either mobile app, but that should change. I think you can just swipe the web code for this, as it'll be pretty straight-forward to use the graphing libraries.

**Comment by Dejal** [comment]
Do you mean the "Site Statistics" sidebar on the website home page, with the Past Day and Past Day by Hour stats? I'm not sure how useful that'd be to iOS users, but some might be curious.  Or did you mean something else?

Where would you like it to appear? I could display a web view, perhaps pushed from the main menu (with Preferences etc), or via the profile button at the top.

Is there a way to get a web page with just that content?  I don't think it'd be a good idea to try to run Python scripting to render it on-device, as Apple has said that such scripting support will go away in a future OS version. If you could provide a URL for a small page with just that block, that'd be ideal.

_(I'm working on NewsBlur now, so could get this in within the next day or two, once you clarify.)_

**Comment by samuelclay** [comment]
I meant the Statistics dialog, which you can see by right-clicking a feed title and opening Statistics.


<img width="654" alt="Screen Shot 2019-09-18 at Sep 18 5 30 19 PM" src="https://user-images.githubusercontent.com/44229/65187539-28dc5f00-da3a-11e9-9a2d-bac2e5e7071b.png">

<img width="581" alt="Screen Shot 2019-09-18 at Sep 18 5 31 28 PM" src="https://user-images.githubusercontent.com/44229/65187549-2d087c80-da3a-11e9-9384-3f3774e0b3f3.png">

**Comment by samuelclay** [comment]
And yes, this should be a webpage. That way we can just crib from the web's reader_statistics.js

**Comment by samuelclay** [comment]
Thinking about it more, it seems a server-side webpage would be a good idea. That way we can use it on Android (#1239) just the same. I guess hold off on this until I built that then.

**Comment by Dejal** [comment]
Ah yes. Users would find that quite useful. But yeah, a stand-alone server-side web page would be best to display that content. 

If you can, ideally with theme support: have a URL that takes a feed ID and theme parameters, at least light and dark options, so it isn't blinding on dark devices.

I'll wait till you have something ready.

**Comment by Dejal** [comment]
While you have some time for web changes; a reminder of this one.

**Comment by samuelclay** [comment]
Done: https://www.newsblur.com/rss_feeds/statistics_embedded/1024

**Comment by samuelclay** [comment]
Can we use the statistics icon from the web? Also, can we add it to the feed swipe options?

**Comment by Dejal** [comment]
Do you mean when you slide a feeds list item towards the right to reveal the notification option? Does that support multiple options?

**Comment by Dejal** [comment]
Okay, looks like it does support two. The left-side swipe also uses a preference to choose between training and notifications. So would you prefer the statistics is a second (permanent) command in the swipe view, or a third preference option for the one swipe command, to choose between training, notifications, and statistics?

**Comment by Dejal** [comment]
<img width="425" alt="Screen Shot 2020-01-29 at 15 44 47" src="https://user-images.githubusercontent.com/1318849/73407541-5077e980-42ae-11ea-8927-de438b8d6802.png">

**Comment by samuelclay** [comment]
I would just add it as an option to both swipe menus. Actually, both menus should have the same options, so marking read should be on both as well. No need to change the defaults though.

**Comment by Dejal** [comment]
Do you mean the right-side swipe option on the feeds list? It doesn't have a preference; it is always mark read.  Which seems reasonable, since that'd be a very common action.

Do you want me to add a preference for that, with the same options as the left side?  (i.e. training, notifications, statistics, and mark read as options for both.)

**Comment by Dejal** [comment]
Unrelated, an observation: the statistics sometimes has a "if you went premium" message, when I'm a premium user. It doesn't show that on the web. We should add a parameter to the statistics URL to indicate that the user is premium, and omit that. 

<img width="412" alt="Screen Shot 2020-01-30 at 20 08 33" src="https://user-images.githubusercontent.com/1318849/73511906-55b36200-439c-11ea-8f2e-15766f71424a.png">

While you're at it, it'd be great if you could support a dark mode parameter too, if feasible (I know the website doesn't support that yet, but doing it for that one page may not be as hard).

**Comment by samuelclay** [comment]
> Do you mean the right-side swipe option on the feeds list? It doesn't have a preference; it is always mark read. Which seems reasonable, since that'd be a very common action.

Yeah, you're right. Ok, just add it to the left side. I figured we could give ultimate options, including options for long press. But nobody's asking for it, so don't bother.

**Comment by samuelclay** [comment]
I need to change the font sizes on the stats dialogs if we're going to ship it. It's too tiny right now. I'll take out the premium messaging.

**Comment by samuelclay** [comment]
Ok, I'm writing up release notes cause it's time for this version 10.0 to go out and get blogged. Can you fill me in on everything we did that's not these:

* Statistics dialog
* Widget
* Do text view stories download in the background?

**Comment by Dejal** [comment]
In addition to the statistics and widget, since version 9.1 there was also:

- Fixed crash on start. (#1258)
- Fixed highlighting issue. (#1257)
- Fixed settings with stories on bottom. (#1254)
- Tweaked dark theme colors to be darker. (#1249)
- Fixed wonky behavior. (#1215)
- Added a "Download text" preference.  Defaults on.  If on, the text is fetched for feeds that are in text view when fetching new stories.  When displaying a text view, the cached text is used if available, otherwise it is fetched as before. (#1236)
- Unsubscribe feed from story. (#1262)
- Clearing offline now clears the cached stories, text, and images from the database. (#1266)
- Manually changing the theme now turns off the preference to follow the system appearance.
- Turning on following the system appearance immediately updates the theme appropriately. (#1268)
- Fixed crash on feed load list. (#1271)
- Preferences import & export.

Plus working on a few other issues that didn't have notable changes.

Hope this helps.
