### ISSUE TITLE
iOS: Folders don't match web

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1260]
User support request: https://twitter.com/reybango/status/1187434445663399936

Try logging in as the user to replicate (username is the same).

**Comment by Dejal** [comment]
His **Move to Another Folder** options do match his folders, in both his screenshot and logging in as him.  (Don't think I can log in as him on the website?)

A possible source of confusion: some are in subfolders, e.g. an item that appears as "TECH" in the Move To popover is "GENERAL - TECH" in the feeds list, indicating a TECH subfolder of GENERAL, though there isn't a separate GENERAL listed, so it's either a folder with only that subfolder, no feeds, or the fun old #1043 again.

That's how it's loaded from `flat_folders`:

```
        …
        Development =         (
            71954,
            6188684,
            5973611,
            5928796,
            6384810,
            1839
        );
        Fitness =         (
            2851972,
            6277120
        );
        "General - Tech" =         (
            576138,
            6232309,
            7219858
        );
        …
```

May need further clarification.

**Comment by Dejal** [comment]
- Fixed the long-standing issue of folders misbehaving if they have a `“ - “` in their name, since the server uses that to indicate child folders.
- It now replaces that with `“ ▸ “` if there is actually parent folder, which as a bonus looks better when displayed.

![Simulator Screen Shot - iPhone 8 Plus - 2021-04-23 at 13 36 59](https://user-images.githubusercontent.com/1318849/115927424-43a65f00-a439-11eb-85c0-ba135b588971.png)
