### ISSUE TITLE
Android: image feed should use same proxy as web version

### ISSUE THREAD

**Issue by lidel** [samuelclay/NewsBlur#1267]
When I open a feed on desktop, Images embedded in the port are displayed via proxy:

https://images.newsblur.com/643629380131d3ec52c0315d8d681d63fc76b8b0/687474703a2f2f61737365742d362e736f757063646e2e636f6d2f61737365742f31343438362f313539375f366265375f3430302e6a706567

When I open the same feed in Android app, images open slower and/or are often broken due to TLS misconfiguration because direct links are used:

https://asset-6.soup.io/asset/14486/1597_6be7_500.jpeg

Is there a reason why image proxy is not used on Android? 
I believe it would improve use experience a lot.

**Comment by samuelclay** [comment]
I agree that it can be faster in some cases, but since the device can load https urls just fine, I'm not going to add extra load on the server if it's unnecessary. That said, I'm not terribly against this, since it would literally be a one line change (substitute each `secure_image_url` per story), but I'm not sure it would make anything faster and if anything would slow down other requests as the secure image proxy would be doing a whole lot more work than it is now.

**Comment by lidel** [comment]
What if mobile app does fallback to proxy only if original URL fails to load?
It would solve those flaky soup.io image feeds without putting unnecessary load on proxy.
