### ISSUE TITLE
iOS: Swiping between stories is slow

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1277]
Looks like related to #1162, but I wanted to separate this out cause it felt like a different enough bug. Anyway, try swiping between a dozen stories. For me, about a third of them take 2-3 seconds of stop-the-world loading. See this video:

https://www.dropbox.com/s/v00qinopzj8ttr4/RPReplay_Final1579830224.MP4?dl=0

**Comment by Dejal** [comment]
Hmm. I can't reproduce that on either my iPhone 11 Pro Max or an iPhone 8 in the Simulator.  I can swipe or tap Next without delay.

I tried logging in as you on my iPhone, and it still worked smoothly.  (I restored the unread state on those stories afterwards.)

I can't think of anything related to the widget that could affect story swiping.

I'll try again tomorrow.

**Comment by samuelclay** [comment]
Don't worry too much about unread status. I don't pay attention to those things, I just use the firehose of the river of news.

**Comment by Dejal** [comment]
I still can't reproduce this issue. I wonder if it is related to some preference?

Since comparing the settings is tricky, I've added new options in the Preferences view to import and export the preferences.  They can be saved to iCloud Drive or other providers.  Please export your preferences and send to me, and I'll import and see if that helps reproduce it.

These new features could be very useful for users, to manually sync settings between devices.  But if you don't want them, we could hide them.

**Comment by samuelclay** [comment]
Seems to be working fine now. Thanks for checking!
