### ISSUE TITLE
[API] in_folder in /reader/delete_folder isn't optional?

### ISSUE THREAD

**Issue by quanganhdo** [samuelclay/NewsBlur#1291]
When I tried to call `reader/delete_folder` with only `folder_to_delete`, I got a 500 Internal Server Error page.

Adding `in_folder` with any value fixed the issue.

This seems to be contradict with the API doc, which says `in_folder` is optional.

**Comment by samuelclay** [comment]
Yeah it is optional. Looking at the code tells me it is. Whatever the error is, it's not related to the in_folder value missing, it's due to something not working right. I wish I had caught this when the logs were still fresh so I could find out what the actual error is. Thanks for reporting this!

Here's the relevant code:

https://github.com/samuelclay/NewsBlur/blob/master/apps/reader/views.py#L2074
