### ISSUE TITLE
iOS: Feed both has and doesn't have a story permalink

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1293]
https://www.icao.int/EURNAT/_layouts/15/listfeed.aspx?List={EA308982-6751-4B79-BD3B-566101019137}&View=88fb0350-edc0-4c78-8b87-524e5bd14df1

Tapping on the Safari button gives a different result than tapping on the story title.

See https://forum.newsblur.com/t/ios-opening-source-strange-behavior/8087

**Comment by Dejal** [comment]
The reason is that the `story_permalink` is `https://www.icao.int/EURNAT/EUR and NAT Documents/Forms/DispForm.aspx?ID=2500`, which is an invalid URL, since it contains spaces.

(You might want to do some server-side validation of that?)

When displayed in the web view, it is properly escaped by the renderer, so works.

I'll check for that and use an escaped URL.
