### ISSUE TITLE
Docker: Single command line install of NewsBlur

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1316]
Let's fix the Dockerfile and make a single command line install of NewsBlur, complete with DB dependencies.

**Comment by Germs2004** [comment]
May I suggest adding automatically updated, pre-built Docker images to DockerHub, similar to tt-rss and [FreshRSS](https://hub.docker.com/r/freshrss/freshrss/)?  It would make installation easier for users who prefer not to build locally.

**Comment by samuelclay** [comment]
What commands would you want to see in the `README`? I don't run NewsBlur containerized myself so I'd be interested to hear how you would expect it to be run?

**Comment by Germs2004** [comment]
I've never used NewsBlur so it would be great if some other users would comment.  I'm just here because I wanted to compare NewsBlur with tt-rss, and I was hoping for a quick simple docker install.  Since I couldn't find it, I figured I'd leave my +1 on this issue and check back later.

But my opinion:

**Automated builds:**
Have an automated build system that automatically sends an image to DockerHub with the tag "dev" every time any code change gets checked in.  Have another automated build that sends an image with the tag "latest" every time a tested release gets published, so the users who subscribe to that tag can always keep their docker container running your latest release.

**Simple standalone pre-built docker image:**
The automated build should be a docker image that just installs the plain NewsBlur app.  The image should let the users specify a hostname, database credentials, etc to point the NewsBlur app to any database we want.

**Feature-complete docker-compose**
Have a docker-compose.yml file that includes that standalone pre-built image, plus the database, plus all the other stuff NewsBlur needs.  Ideally, the optional pieces (redis and elasticsearch?) should be optional so if a user does not want redis, they can comment that out of the docker-compose file and NewsBlur will still run happily without it.  The current docker-compose file in your GitHub has a "build" section, which IMO should be removed and replaced with pre-built images.

You could check out what some other projects are doing on DockerHub.  LinuxServer is a popular organization that creates really good docker images. It takes some time to get everything set up initially, but the upkeep is mostly automated and having good Docker support will probably eliminate 90% of user confusion and questions about installation.  Even ongoing user support would be easier since every user will have exactly the same version of every component.  From the user perspective, it turns a system with 500 parts into a system with 10 parts.

**Comment by kormoc** [comment]
Personally I'm looking to run it for a single user, so for myself, a Simple standalone pre-built docker image that I bind mount a data directory for the database would be ideal. I don't even care to configure anything beyond the basics as required.

**Comment by JasonGhent** [comment]
While it's not the most thorough or vetted implementation, I have a [Makefile here](https://github.com/JasonGhent/NewsBlur/blob/cypress/Makefile) that will not only do a single-command standup of NewsBlur, but also enforces an e2e test that the instance will allow a user to sign up successfully. YMMV. Let me know if anyone finds this useful and/or has any questions or feedback.

**Comment by samuelclay** [comment]
Take a look at the `docker_django3.0` branch which has the latest code. If you want to propose any changes, please submit a PR to that branch. We're actively working on it and would appreciate all the outside input we can get.

**Comment by ttimasdf** [comment]
Could I migrate the DB of an existing setup to `docker_django3.0` branch? Hopping it to be backward compatible.

**Comment by samuelclay** [comment]
> Could I migrate the DB of an existing setup to `docker_django3.0` branch? Hopping it to be backward compatible.

It will be backwards compatible. We're working this week and next on migration. We'll also document in the README how to accomplish that. cc @jmath1

**Comment by samuelclay** [comment]
This is now ready to launch. Use the `dashboard3` branch and if you want to re-use an existing DB, you'll need to edit the docker-compose to add the volumes and change to the correct versions.

**Comment by zero77** [comment]
@samuelclay 
Are there any plans to release an official Docker Image on DockerHub, or update the existing one.

https://hub.docker.com/r/newsblur/newsblur
