### ISSUE TITLE
Android: Built in browser

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1319]
See this forum thread: https://forum.newsblur.com/t/android-built-in-browser-because-twitter-videos-doesnt-play-on-android/8177

On iOS we give users an option of using an in-app browser or use the full Safari browser with an app switch. Android should have a similar preference.

**Comment by samuelclay** [comment]
This is great! Can we add a way to immediately come back to the story? I found that using the in app browser I would go in a few links and then have to completely unwind them. Also, swiping back from the edge wasn't working, although that may be an iOS only feature.

**Comment by samuelclay** [comment]
Also, the in app browser should be used when tapping on the story title while in the story detail view (and not just the links in the story content).

**Comment by sictiru** [comment]
Swiping from the edge should close the page, similar to a back button action. Are you seeing a different behavior? 
Also now it will close without needing to unwind links

**Comment by whispy** [comment]
When will this be released to the production app? I looked through the commits but didnt see anything about a release tag or schedule.

**Comment by samuelclay** [comment]
I just released it today as part of v10.1b5 on the beta channel. Switch to beta and let me know how it's working.

**Comment by whispy** [comment]
@samuelclay it's working great so far! There are just 3 areas that could be improved:

1. I think the back button should unwind links instead of going directly back to story. But, that's personal preference.
2. User should be able to copy the URL of the currently viewed page (e.g. if they navigate several links deep past the story and want to extract the URL for archiving or sharing)
3. User should be able to tap-and-hold to copy inline links.
