### ISSUE TITLE
Backend: Python 3

### ISSUE THREAD

**Issue by cyranix** [samuelclay/NewsBlur#1323]
Not critical from a daily-use perspective, but the Python world is moving on from Python 2. Since this codebase uses Python 2, there's an upper limit for dependency upgrades and security patches.

As a paying user since 2011, I'd love to see evidence of a plan to upgrade to Python 3, so that I can have confidence about the future of the product.

**Comment by samuelclay** [comment]
We've been working on it for the past month. First Django being upgraded to v3.0 (currently at v1.5, but we are up to v1.8 on the django1.8 branch), then Python, then Docker. I have a new backend developer helping me do this work and I expect it to take no more than a month, esp. as I'm now full-time on NewsBlur again.

**Comment by samuelclay** [comment]
We're working diligently on it! Go ahead and run the docker_django3.0 branch and run `make` and see how that works for you. The work is mostly done, we're just trying to find all the bugs right now. And anything new should be implemented against the docker_django3.0 branch, since that is going to become the main branch before the end of the year.

**Comment by samuelclay** [comment]
I'd say this is ready to go. Use docker-compose (see the README) and you should now be all set. This will hopefully launch soon. Try it out at beta.newsblur.com.

**Comment by samuelclay** [comment]
Oh you'll want the dashboard3 branch for this. I'll delete the others now.
