### ISSUE TITLE
iOS: Full screen with status bar shows toolbar popping into view on scroll

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1329]
Turn on status bar while in full screen and ensure there's multiple long stories in a row. As you scroll horizontally between them (once you scroll down enough to enter full screen mode), you then see the toolbar for a split second as you scroll down the full screen story. Happy to capture a video.

**Comment by samuelclay** [comment]
As a note, once these four issues (#1329, #1330, #1331, and #1332) we'll ship out the next update. But on full screen, would it be possible to have the toolbar attached to scrolling instead of sliding out of view? Sort of like how the story traversal buttons are attached to scrolling at the bottom of a story.

**Comment by Dejal** [comment]
Do you mean having the bar interactively scroll away with the content, like in Safari etc? We could do that if we adopted the native hiding features, instead of fighting it — which would let us strip out a bunch of custom behavior.

**Comment by samuelclay** [comment]
Yes, that would be ideal

**Comment by Dejal** [comment]
Okay, I've just committed incomplete changes to change the fullscreen behavior to use the iOS conventions:

- The story fullscreen function now uses the standard behavior, like in Safari and other apps, where the navigation bar scrolls away with the content, and a quick swipe down or up shows or hides it, respectively.
- When auto-scrolling is not enabled, a tap in the story will toggle the bar.  When auto-scroll is enabled, it briefly shows the auto-scroll controls, as before.

Currently there is some incorrect behavior when hiding the navigation bar with the status bar shown; I'll fix that in the coming week. I just wanted to commit this now to check that you're okay with the new behavior, since we went through several iterations in the past. Other than those minor issues, I think it works much better than before.

**Comment by samuelclay** [comment]
I like how the navbar scrolls away, but there is still some jumping that is happening. Also the feed bar isn't shown as I swipe between stories. Also, let's add a background to the status bar, since I don't like the look of story text underneath the clock. Looking forward to this week's fixes!

**Comment by Dejal** [comment]
Yes, the feed bar and status bar background are the remaining issues I haven't fixed yet. Positioning them properly during the transitions are tricky, so I hid them for that commit. I'll fix those this week in between watching WWDC videos.
