### ISSUE TITLE
iOS: Full screen mode toolbar appears and disappears

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1338]
There are a few oddities with the toolbar in full screen mode that I'd like to address.

Can we attach the toolbar to the top of the story and have it scroll both in and out of view? It seems like it scrolls out of view but is then detached. If it were attached the entire time, it wouldn't require any changes to the scroll bar or scrolling speed. I expect the toolbar to come back when I scroll back up but instead I'm seeing some wonky behavior with it appearing and disappearing. 

What I'm trying to avoid is any bounce to the story content itself. As I scroll up and down and the toolbar disappears and reappears, it's causing scrolling to bounce around instead of directly staying with my finger.

**Comment by Dejal** [comment]
I don't think there's anything I can do to improve that behavior. It is now using the standard iOS API to hide and show the navigation bar on scrolling, so the way it works when doing that is up to Apple.

I've actually spent quite a bit of time beyond the monthly amount on getting this to work as well as possible; making the feed bar and status bar background behave in a fairly reasonable way was very difficult.

If you can provide a screen recording of a specific behavior that you don't like, I could try to improve it next month, though no promises.

**Comment by samuelclay** [comment]
Thanks for going extra on this. I'm hoping to get the scroll dynamics of NewsBlur on par with the other big competitors (like Reeder) and it's these small details that I want to get right. Happy to go over for the month if you have the time to spare.

Here's a video showing two bugs. One is the missing feed bar, and second is the snap back.

https://www.dropbox.com/s/he2qjjx96x4i5jz/RPReplay_Final1593474142.mov?dl=0

**Comment by Dejal** [comment]
The feed bar scrolls away with the nav bar, and I re-show it once you stop scrolling. I tried for some time to constrain it to the visible area, without success. I have to wait for scrolling to stop, otherwise it appears too low, as the view offset changes when starting hiding the bar, even though it is still partially visible — there is a disconnect between the theoretical position and the actual position. There may be a way to hook into that interactive animation, but I couldn't find it.

The snap might be a result of redrawing it, so I might be able to improve that, though not sure.

I don't have any more time available this month (or brain cells to melt on this), so I'll come back to it next month, if you don't mind.

**Comment by Dejal** [comment]
It isn’t perfect, but I’ve spent a lot of time trying to get it tolerable in the various paging directions and fullscreen options. I’ll probably want to revisit this when doing the three-column layout changes (#817), since that'll be an opportunity to modernize the paging mechanism.

I'll leave this open for now.

**Comment by Dejal** [comment]
The work for the Catalyst edition will improve this; see #817 for more info. So I'll close this.
