### ISSUE TITLE
iOS: Search box loses focus

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1344]
See https://forum.newsblur.com/t/ios-search-box-is-broken/7664/3

**Comment by samuelclay** [comment]
So the user, rightfully, mentioned that this should have gone out. But the problem is that it was on top of other UI changes and so I'm wondering when you think we'll be ready for a release. I've noticed that we're building a lot but there's never a clear moment for a release. Would you be alright with noting that you feel a build is ready for release so I can give it a full test and then we'll fix any remaining issues.

Right now we're waiting on a rather substantial UI refresh but what is your estimate on a release? Can we cherry pick?

**Comment by Dejal** [comment]
The changes in the **Dejal** branch should always be in a releasable state, at least at the end of each month. You are welcome to merge them into master and release at your convenience. If I'm working on a bigger project that might not be finished by the end of the month, I do so in a different branch (e.g. the **Catalyst** one, or a local one).

Since I tend to do NewsBlur work in the third or fourth week of the month, you could do a release at the beginning of each month if you wish, if there are worthwhile changes. There will be a couple week period when I'm not changing anything, so is safe to release. (A guaranteed indicator I'm done for the month: when I send the invoice.)
