### ISSUE TITLE
Pull to refresh in feed detail

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1357]
Mentioned in #1304:

> That's because there is no pull-to-refresh in the feed detail. I suppose we could add it...

I've added pull-to-refresh there, but only for feeds, not folders, since the latter requires logic tied to the feeds list. For feeds, it basically does an instafetch.

**Comment by samuelclay** [comment]
Ahh, I now remember we used to have this feature. I turned it off because some users were using it constantly and I felt bad for them as they were being conditioned to think that NewsBlur was broken because stories would come in after their pulled to refresh even though ostensibly NewsBlur should be fetching stories often enough.

**Comment by Dejal** [comment]
Yeah, kinda like those people who insist on force quitting all their apps.

Do you want me to roll it back, or leave this change in? (I'm fine either way; whatever is best for the app.)

**Comment by samuelclay** [comment]
Leave it in, I think it's a fine convention.
