### ISSUE TITLE
iOS: Preference to not allow any audio (or to stop auto-playing audio)

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1362]
Can we figure out how to either turn off audio or to prevent auto-playing audio? Here's the forum post: https://forum.newsblur.com/t/newsblur-cuts-off-background-audio/8035/5

**Comment by samuelclay** [comment]
I should note that the forum post is actually about a different issue where background audio is stopped on app launch. We should fix that as well but I'm not sure it's still happening. I couldn't repro it.

**Comment by samuelclay** [comment]
Another forum post:

https://forum.newsblur.com/t/feature-request-autoplay-off/9103/2

**Comment by samuelclay** [comment]
Another forum post: 

https://forum.newsblur.com/t/embedded-youtube-clips-sometimes-auto-playing/8922/4

**Comment by Dejal** [comment]
I can't reproduce this. I tried the suggested feeds like boingboing.net, rexwordpuzzle.blogspot.com, and several others with embedded videos, like my own sinclairtrails.com. None of the videos auto-played. I think this might have been fixed by the transition from the legacy WebView to WKWebView.

So I'll close this, but feel free to re-open (with an example) if you get any future reports, or can repro it.
