### ISSUE TITLE
Android: Notifications resent when app is opened and story isn’t marked read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1369]
From the forum: https://forum.newsblur.com/t/android-notifications-resent-when-app-is-opened-and-story-isnt-marked-read/8355

Let's get this fixed if we can reproduce it. Figuring out how to reliably reproduce it is key. User reinstalled the app to no avail.

**Comment by sictiru** [comment]
@samuelclay 
There is a flag I can set in order to play sounds and/or vibrate only once per notification batch. Basically there won't be a new sound and/or vibration if there are other active notifications already posted from NewsBlur. Sometimes there are multiple audible alerts fired and this flag will solve it. 

The other issue with the resent notifications will happen if I get a notification, I don't interact with it at all (save/dismiss/mark read/open), the app gets killed in the background and I reopen the app. The previous flag that I mentioned should fix this too in the sense that the user won't be actually alerted again by the notification. Alternatively I could skip the alert if it's already shown which is probably better.

Another thing that I want to point out is that I can receive notifications for stories that are old (>3d) after I enable notifications for feeds with unread stories. Should we put a limit on the timestamp?

**Comment by samuelclay** [comment]
Yep, let's put a limit on the timestamp.

**Comment by sictiru** [comment]
I'll limit them up to 48 hrs
