### ISSUE TITLE
Android: Add theme buttons to manage menu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1378]
Similar to iOS, I'd like to have the theme colors represented by circles t=in the manage menu. Here's a screenshot:

![IMG_D592ABA08B97-1](https://user-images.githubusercontent.com/44229/96303916-3d868000-0fc9-11eb-9d39-af17607c919b.jpeg)

This came up as part of this ticket: https://forum.newsblur.com/t/ui-suggestions-for-the-android-client/8401

**Comment by sictiru** [comment]
@samuelclay this is one area where there is a difference between how Android and iOS use popup menus. The text size is not the same on Android either. This can probably be achieved but with a significant refactoring because that popup is present in a few places in the app and it would need to be fully custom. If you don't feel strongly about this, I can provide some alternatives.

**Comment by samuelclay** [comment]
Yeah I don't feel too strongly about this. Open to any suggestions. At the very least, let's move Theme up a few notches, as per the discourse thread.

**Comment by sictiru** [comment]
Current: 

![Screenshot_20201108-182611](https://user-images.githubusercontent.com/13900221/98494813-b062cf80-21f2-11eb-9760-3b4de68a4936.png)

Proposal:
 
![Screenshot_20201108-183137](https://user-images.githubusercontent.com/13900221/98494819-b48eed00-21f2-11eb-8ab3-ef9a03b0c8b5.png)

'Refresh' could be removed since swipe/pull on the list to refresh is widely used on mobile
'Add new feed' is always available on the main screen via the + symbol in the bottom left corner
'Search your feeds' I think it can be moved at the top within the main screen similar to iOS or as a search icon within the toolbar in the top right corner (similar to story list screen on Android)

With these changes the UX is minimally impacted and it makes for an easier options list to go through. The rest of the options were rearranged.

**Comment by samuelclay** [comment]
That's a lot cleaner. Looks good!
