### ISSUE TITLE
Android: Automatic light/dark theme setting

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1379]
Correspond with the system theme. On iOS, we have an auto setting, pictured here:

![IMG_7903554BBEEC-1](https://user-images.githubusercontent.com/44229/96304107-85a5a280-0fc9-11eb-983b-7a5ab693624f.jpeg)

From https://forum.newsblur.com/t/ui-suggestions-for-the-android-client/8401

**Comment by samuelclay** [comment]
Oh the user also mentioned that the bottom bar is white even in dark mode sometimes. Not sure what that's about but we should fix that.

**Comment by sictiru** [comment]
The OS based auto theme has been recently built but it might still be in the beta versions.
I will check the bottom bar theme because based on the phone's manufacturer/OS it might need explicit coding.

**Comment by sictiru** [comment]
I changed the default theme setting to Auto instead of Light to apply the global OS setting out of the box.

@samuelclay For the bottom navigation bar I couldn't find a solution that works well with the current deprecated theme on all API versions. This can be easily fixed after updating the theme, something that I also mentioned here https://github.com/samuelclay/NewsBlur/issues/1353. I'll create a separate issue for that and start on it soon
