### ISSUE TITLE
Import saved/unread Feedly articles into NewsBlur

### ISSUE THREAD

**Issue by harabat** [samuelclay/NewsBlur#1393]
Hey NewsBlur team,

Spent some time looking for a way to import unread/saved articles into NewsBlur, but haven't found one. I can't be the first person with a pile of unread stuff making the jump from Feedly to NewsBlur, so I assume that there is a solution somewhere, or that there's a technical obstacle. 

If it's neither, then I could write up a script to do this. Feedly has an API and allows to export Saved articles (_Settings/Privacy and Personal Data/Take Your Data With You/Generate your personal data archive_), NewsBlur has an API, seems possible. Any advice before I start working on this?

EDIT: if it's unclear, I am talking about importing the saved articles, not the feeds. 

Cheers!

**Comment by carlosflorencio** [comment]
Hi,

Feedly has an option to export an opml file that you can import into NewsBlur: https://feedly.com/i/opml.

More info:
https://blog.feedly.com/opml/

**Comment by harabat** [comment]
Hi @carlosflorencio,

The OPML file contains the feeds, but not the articles. 

The issue I am raising here is that I assume a lot of people have a large backlog of saved articles, which acts as an obstacle to moving to another service. Feedly allows to export the backlog or to query it through the API (as explained in my original message), but importing it into NewsBlur (or another service) is not straightforward, which is why I'm offering to write up a script: to further ease the transition from Feedly to NewsBlur. 

Cheers.

**Comment by samuelclay** [comment]
I tried to get a Feedly API key but was unsuccessful. Looking at it now it seems that you can either use a developer token, which is limited to 25 calls a day, or an enterprise token, which has to be user specific.

I'll say this, NewsBlur has no limits on its API and can handle as many saved stories as you send it. It's easy to get working, using either cookies (the newsblur.com/api page describes this, but just call /reader/login first and your calls will all be authenticated) or using OAuth. The Feedly side will be trickier, as you'd need to batch all of your calls. 

Since you have a data export, you might be able to build a quick json reader that exports to NewsBlur's API. You'd only need a few fields: author, content, permalink, title, tags, save date, publish date. 

Let me know how I can help! just post on this thread and I'll see what I can do. And please let me know how it works out.
