### ISSUE TITLE
Fdroid build problem

### ISSUE THREAD

**Issue by jugendhacker** [samuelclay/NewsBlur#1408]
I'm currently trying to package v10.2.0 (version code 179) for F-Droid. I just noticed that 00ad1612fb9976b34ff57cc8a0f153e423a7f739 adds the play core as dependency. This is problematic because it is proprietary and F-Droid will not add software containing proprietary parts. In my mind there are two solutions to this problem:

1. add a FOSS build flavor which does not include the play core
2. remove the in app reviewing part completely

**Comment by samuelclay** [comment]
How hard would this be to separate during the FDroid build process? If you write a script that does the separation and can guide us as to any changes you'd like us to make, we'd be happy to include them. But the in-app review is necessary from a business standpoint and we've never dealt with the FDroid release. Since NewsBlur is 100% open-source, it makes sense that you should be able to take out what you need. 

If that means moving all of the business logic (and imports) for the in-app review to another file that can be easily dropped from compilation for FDroid, submit a PR and we'll work together to integrate it.

**Comment by jugendhacker** [comment]
Okay to adding a build flavor without the review is most likely what is needed. I'll try to develop this and submit a PR then, okay?

**Comment by samuelclay** [comment]
That sounds great! @sictiru will be in charge of merging and approving.

**Comment by samuelclay** [comment]
Feel free to re-open if you've got a PR.
