### ISSUE TITLE
iOS: Back button not working in Full Screen mode

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1488]
See screenshot. I can't get back to the feed list without edge swiping from the left. That back button should bring back the feed list.

![IMG_404F547005CB-1](https://user-images.githubusercontent.com/44229/119563201-45837b00-bd75-11eb-8fb1-4c6582687f7d.jpeg)

**Comment by samuelclay** [comment]
Also it would be nice if the theme for that back button matched.

**Comment by Dejal** [comment]
Unfortunately I don't think I can fix this one. The back button is managed by the `UISplitViewController`, and not exposed via API. I've seen other reports of the same issue; it could be considered an iPadOS bug. Perhaps they'll fix it in the next iPadOS update?

I could remove the back button, but that will also disable the swipe gesture, which isn't acceptable.

I tried to go spelunking through the view hierarchy to find the button and manipulate it, but (a) that is generally a dangerous thing to do, since it can change or get the app rejected, and (b) it didn't really help, as the back button is implemented by a private view. I left the experimental code commented out in the above commit, just in case.

So we should probably ignore this issue for now, and hope they fix it.
