### ISSUE TITLE
Android: Custom domain not added to imageproxy path

### ISSUE THREAD

**Issue by Linecutterx** [samuelclay/NewsBlur#1602]
On the web interface I see an image with a source of 

> https://<my domain>/imageproxy/sc,sfJ_Vn9fP69ggB3l572DqmhzVEJ4EZZUkMaTYBgIUVrA=/http://www.nasa.gov/sites/default/files/thumbnails/image/march2014_1920x1200.jpeg

but the android app shows a broken picture icon, with a source that is shown as 

> /imageproxy/sc,sfJ_Vn9fP69ggB3l572DqmhzVEJ4EZZUkMaTYBgIUVrA=/http://www.nasa.gov/sites/default/files/thumbnails/image/march2014_1920x1200.jpeg

i.e. missing the https://<my domain>

Haven't had a chance to test against an iOS device.

**Comment by samuelclay** [comment]
Well the real issue is that the Android app has no way of reaching a local imageproxy server unless you've exposed it to the world. In which case, you'll need to change your settings:

Either change in settings.py or in docker_local_settings.py, depending on how you've got your custom server configured.

> IMAGES_URL   = 'https://imageproxy.newsblur.com'

**Comment by Linecutterx** [comment]
You're totally right! (& I'd fixed it by changing the reverse proxy settings, then forgot to close this issue. Sorry!)

**Comment by Linecutterx** [comment]
So, if I read that correctly:
The haproxy redirection of the path /imageproxy  (which works for the web interface) needs the docker_local_settings.py changing in order for it to function for the android access. Otherwise no domain is added to the link to get back to haproxy.
Should IMAGES_URL be set to <my domain>, or <my domain>/imageproxy? It's set to /imageproxy by default, so I assume the latter.
Looks like I'll need to tweak the custom domain script/instructions - I'll get it right here (although I'd still like the clarification :)), then create a pull request.

**Comment by samuelclay** [comment]
You know, it shouldn't matter if it's a relative url, at least on the web. The url is sent to the client and the client can choose what the domain is. On the web, it's the relative domain. On Android, it probably fails because it isn't being interpreted as a relative url. So it needs that custom domain explicitly written out. 

But @sictiru, do you think the substitution for `secure_image_urls` could include the custom domain if set?

**Comment by Linecutterx** [comment]
MEDIA_URL = '/media/' #leave this alone or it all goes wrong!!
IMAGES_URL = NEWSBLUR_URL + '/imageproxy'

Works for web & for android (well as far as I've checked!).
I'll tweak the sed script...

**Comment by sictiru** [comment]
@samuelclay The custom domain can be included in the substitution if needed.
Would something like
`if (isCustomServer && !url.startsWith("http") then url = "{custom server base url}/imageproxy"` work?

**Comment by samuelclay** [comment]
Yep, that sounds great. Let us never change that url.
