### ISSUE TITLE
How to keep a standalone NewsBlur docker installation up to date?

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1612]
how do you update the newsblur app when running via docker? not talking about updating feeds, but the app itself, or one of its associated containers(?)…

**Comment by samuelclay** [comment]
Two ways:
1) Keep the code up to date by running `git pull` periodically`
2) Keep the database up to date by running `make nb` after pulling down changes.

**Comment by luxiouronimo** [comment]
heya, my `make nb` resulted in a migration error…

…

```
> docker exec newsblur_web ./manage.py migrate
> Operations to perform:
>   Apply all migrations: admin, analyzer, auth, contenttypes, feed_import, ipn, oauth2_provider, profile, push, reader, recommendations, rss_feeds, sessions, sites, social, zebra
> Running migrations:
>   No migrations to apply.
>   Your models have changes that are not yet reflected in a migration, and so won't be applied.
>   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
> docker exec newsblur_web ./manage.py loaddata config/fixtures/bootstrap.json
> Installed 8 object(s) from 1 fixture(s)
```
so i do a `python manage.py makemigrations` which results in:

```
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named django.core.management
```

which is the same result for subsequently doing a `python manage.py migrate`

**Comment by samuelclay** [comment]
You can't run `python manage.py migrate` without using the docker container. That's why above shows `docker exec newsblur_web ./manage.py migrate`. But you shouldn't need to run makemigrations because I do all that for the repo. 

Anyway, there's no error message there in the first code block, it's just a warning, and one that I've fixed in the pro branch (which shouldn't be used but will eventually be merged into master).

And to fix the browser errors, run `make collectstatic`. I should turn `DEBUG_ASSETS` to True in docker_local_settings.py for you, but you can change that yourself. You'll see both lines there, since I switch them back and forth.

**Comment by luxiouronimo** [comment]
excellent, the site is loading now..

the browser does however still report a few errors; is there something i can do? the 'websocket connection failed' fires repeatedly..

`DEBUG_ASSETS` is True in docker_local_settings.py (i didn't change it) and i did run a `make collectstatic`.

```
> [Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (fonts.css, line 0)
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (socket.io.js.map, line 0)
> [Log] ["Navigating to url", "folder/everything"] (2) (jquery.newsblur.js, line 26)
> [Log] ["Setting refresh interval to every 70 seconds."] (1) (jquery.newsblur.js, line 26)
> [Error] WebSocket connection to 'wss://my.newsblur.subdomain.url/v3/socket.io/?EIO=4&transport=websocket' failed: There was a bad response from the server.
> [Log] ["Setting refresh interval to every 64 seconds."] (1) (jquery.newsblur.js, line 26)
> [Error] WebSocket connection to 'wss://my.newsblur.subdomain.url/v3/socket.io/?EIO=4&transport=websocket' failed: There was a bad response from the server. (x14)
> [Log] ["Setting refresh interval to every 85 seconds."] (1) (jquery.newsblur.js, line 26)
> [Error] WebSocket connection to 'wss://my.newsblur.subdomain.url/v3/socket.io/?EIO=4&transport=websocket' failed: There was a bad response from the server. (x17)
```

etc…

**Comment by luxiouronimo** [comment]
the websocket issue was due to my reverse proxy; enabling the "proxy_wstunnel" module and adding the following apache config fixed it:

ProxyPassMatch ^/(v3/socket.io/)$ wss://10.0.0.26/$1

**Comment by samuelclay** [comment]
You're running the docker-compose haproxy behind Apache? That's interesting, but that means you had to tell haproxy to use a different port, right? 

Also, websockets are in fact not necessary and newsblur gracefully degrades without them. Websockets were retrofitting on after the non-real-time functionality was built, so that was preserved and websockets take over when they can. If they aren't working, NewsBlur just reloads the feeds every couple minutes or so.
