### ISSUE TITLE
iOS: River is loaded twice on cold start

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1619]
See this video. I've seen this happening quite a bit, so somewhere an extra river load is occurring where it shouldn't be. 

https://user-images.githubusercontent.com/44229/152347211-39720873-0392-4f95-8af7-25f26bbc3891.MP4

**Comment by samuelclay** [comment]
This transition needs to be smoother in all cases. At 0:16, we transition to the story list twice.

**Comment by Dejal** [comment]
I've investigated. The second transition is because the option to show the first story is on. So it loads the feed detail with the offline data, and shows the first story, then fetches the latest stories (in the background; you can see the status if you show the feeds list). Once the new stories are loaded, it updates the feed detail, and selects the new first story. If the load is fast, the new story loads soon after (or even interrupting) the offline one.

I suggest that we should skip loading the first story when loading from the offline stories, and only load the first story once the new ones have been fetched. Especially since the story is now marked as read when displayed, so the offline first story could vanish before actually being read. Let me know if you agree.

**Comment by samuelclay** [comment]
Yeah I agree with that. Better to wait for the online version, since the assumption runs throughout that this is the definitive truth and we ignore the offline version once we get it. Offline is really for when all else fails. 

But sometimes we know if we're offline already. If "Offline" is shown on the feed list, then we should auto-open the first story because we can assume the feed list will continue to be offline.
