### ISSUE TITLE
media/admin resources not found (404)

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1622]
when loading the admin interface, css/js/svg's are not found (404)

/media/admin/css/base.css
/media/admin/js/jquery.init.js
/media/admin/js/core.js
/media/admin/js/nav_sidebar.js
…

this is a docker installation on macos

**Comment by luxiouronimo** [comment]
![Screen Shot 2022-02-08 at 1 48 51 PM](https://user-images.githubusercontent.com/1970784/153081488-3600139c-856c-4df4-894b-516add8a5cae.png)

**Comment by luxiouronimo** [comment]
not sure if #1101 is related, was a while ago…

**Comment by samuelclay** [comment]
It's related in sofar as that is the old symlink for the python2 version and now if you want admin assets, you'll need to run a `make collectstatic`. Did that work in this case? It should take about a minute to run.

**Comment by samuelclay** [comment]
Reason we can't use the symlink anymore if that we are serving assets from the nginx container but the symlink is from the repo to the python virtualenv library dependencies installed with pip, which live on the newsblur_web container. Without exposing pip dependencies without vendorizing them with explicit paths, it's not easy to get the container to talk to each other. 

But the collectstatic sidesteps that and just copies the files. We don't do this as part of `make nb` because it's time consuming and few need it.

**Comment by chippoman** [comment]
My admin interface still isn't loading the resources.

Running make collectstatic is symlinking the admin subfolder files to /usr/local/lib/python3.9/site-packages/django/contrib/admin/static.
