### ISSUE TITLE
Support for NewsBlur by RSS Guard?

### ISSUE THREAD

**Issue by martinrotter** [samuelclay/NewsBlur#1625]
Hello, I am author of RSS Guard, which is multi-protocol and multi-plugin feed reader for desktops - Win, Linux, OS/2, macos, *bsd.

[RSS Guard](https://github.com/martinrotter/rssguard) has plugin-like architecture and already supports some feed readers which provide APIs.

My question is: Would there be interest in me adding NewsBlur support into RSS Guard via your API? If sou, can you somehow estimate how many users would benefit from this?

RSS Guard is FOSS, no fees required, same stands for plugin implementation, I do it for fun in my free time.

**Comment by samuelclay** [comment]
Oh wow, this is amazing! Yes, I'd love to support RSS Guard. We have a larger share of technical users than other news readers, so I would expect a good number of users will at the very least try it out, since it works on nearly every desktop platform.

I'll blog and tweet about it (with screenshots!) when it's ready as well. I'd be happy to support you with q&a and unlimited advice. Feel free to use email or whatsapp. Also, you'll need an OAuth token, so email me your newsblur username and the return url. [You can read more about OAuth on NewsBlur at the API docs](https://newsblur.com/api).

**Comment by jtraulle** [comment]
Hey @martinrotter, does this happened ?

I just downloaded the last version from the GitHub releases page of your project but Newsblur integration does not seem to be present even if presented on the doc page https://rssguard.readthedocs.io/en/stable/features/gui-concepts.html

**Comment by martinrotter** [comment]
@jtraulle Sadly, no. This did not happen after all. Mainly because other stuff was just more important.

Well. NewsBlur, can you somehow make survey among your users, and find out how many users would actually use RSS Guard with newsblur plugin? I would make the plugin, just, to be really sure it is worth it.

Also. RSS Guard already has state-of-the-art Google Reader API plugin! Maybe it would be much faster (maybe?) if NewsBlur devs implemented the API. You only have to implement quite small subset of the API to make it work with many clients, same way Miniflux did.

https://github.com/miniflux/v2/tree/main/internal/googlereader

RSS Guard and many other clients really only need like five methods to provide full-blown two-way synchronization. I could assist in that and make a well-written list of what needs to be done. Or maybe just make the survey. If there would be considerable interest, I can make the plugin, but cannot make any promises tho.
