### ISSUE TITLE
Android: Stack Widget for multiple user preferred sites

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1632]
![Screenshot_2022-02-16-23-56-56](https://user-images.githubusercontent.com/48226312/154331629-72ee8cdd-3357-4bf5-8ca1-c19ff1881597.jpeg)

screenshot source: [Loop Habit Tracker](https://github.com/iSoron/uhabits) app

https://user-images.githubusercontent.com/48226312/154331868-7440ccd2-001e-4570-bf9d-da2a2b96f972.mp4

refer :
https://github.com/iSoron/uhabits/discussions/45#discussioncomment-248128
https://github.com/iSoron/uhabits/pull/346

---

Currently we do support widget but all site feeds mixed in a single widget.

Feature request for additional widget.
- Add option to pick your sites _(just like we have list option for Mute Sites)_ from the list & show each site in Stack view.

**Comment by sictiru** [comment]
@shuvashish76 Once the NewsBlur widget is added to the home screen, under the 3 dots in the right bottom corner there will be a `Widget` option where you can customize and choose the feeds that you're interested in. 
I'm actually intrigued by the stacked widget you posted because the API has a lot of limitations. That would be an interesting and probably long project.

**Comment by shuvashish76** [comment]
> Once the NewsBlur widget is added to the home screen, under the 3 dots in the right bottom corner there will be a Widget option where you can customize and choose the feeds that you're interested in.

Oh! So that option triggered only when you add widget to home screen. 👍🏿 Got it, thankyou...

**Comment by sictiru** [comment]
Feel free to reopen the issue if needed.

**Comment by shuvashish76** [comment]
Do let me know if you add this "Stack Widget" feature in future.
I subscribed this issue thread for future updates.
Thanks :)
