### ISSUE TITLE
Android: Title-only story titles have incorrect height

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1639]
Let's eliminate the vertical whitespace in this view.

**Comment by samuelclay** [comment]
![Screenshot (Mar 4, 2022 11_08_24 AM)](https://user-images.githubusercontent.com/44229/156802090-1b201e0e-52d2-428b-8e31-98aff716c4f6.png)

**Comment by sictiru** [comment]
The white space is there because the image view is taking up the space even if there is no image available for the story. This was intentional and added when the thumbnail style setting (left/right & large/small) were created.
In this case, if the thumbnail style is set to `No image preview`, then the desired behavior will occur.

@samuelclay Should we hide the thumbnail is there is no available image for the feed list or just created a one off special case where if content preview is title only and no image is available, wrap cell around text only?
