### ISSUE TITLE
access to another user's dashboard

### ISSUE THREAD

**Issue by zenodotus280** [samuelclay/NewsBlur#1652]
I'm not sure where else to put this but I ended up getting access to someone else's page. See screenshot below.

![image](https://user-images.githubusercontent.com/16273022/158293835-83db3110-a08a-4f1e-b4a5-f9296549c201.png)

I had limited access but can see far more than I'd expect. No ability to change settings or add new sites.

Accessed by going to: <https://www.newsblur.com/social/39040/MYUSERNAMEHERE> from the "View on NewsBlur" link on <https://MYUSERNAMEHERE.newsblur.com>

Refreshing the page resets it to my own account under a proper SSL connection but I can return to the insecure HTTP one by going back to the link. Going to directly mention @samuelclay here as it is a permissions/privacy issue.

**Comment by samuelclay** [comment]
I'm glad to see you did a very thorough job of describing what is essentially unfinished design choices. What you're looking at here is the demo account. You can tell because it says "homepage" at the top, which is the name of the current user. I use it to allow a new visitor to the website to hit "Try Out NewsBlur" and in pops this feed list. Notice you don't see a dashboard behind the feed list.

I received some feedback a month ago about improving the feed discovery process for sharing urls to people who aren't on newsblur and end up on newsblur.com. What I decide to design for that landing page flow for an individual feed will take this into account, since the homepage user should probably have a big "Sign up now" header somewhere, larger than the small green one.

**Comment by zenodotus280** [comment]
Fair enough. It was the non-https link that made me suspicious and then I thought I was stuck in a weird loop trying to access my own page.
