### ISSUE TITLE
iPad: Column setting doesn't stick

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1682]
See this thread: https://forum.newsblur.com/t/column-layout-setting-on-ipad-doesn-t-stick/9322

**Comment by Dejal** [comment]
I can't reproduce this. If I change the column view mode then exit the app (whether by going home or force quitting), when I re-launch the app, it is in the chosen mode.

iOS saves preferences periodically, including when exiting the app. Even force quitting does so, since that exits to the app switcher. (And people shouldn't force quit anyway.)

The only way I can get it to not save the choice is if I re-run the app from Xcode immediately after changing the option, which wouldn't let any preference be saved. And not something users can do.

Can you repro it? Or get more info?

**Comment by samuelclay** [comment]
User came back with a repro:

> Here’s how to reproduce it on the iPad:
> 
> Set Column layout preference to 3. Test it to make sure it works. This means when you tap a story, you continue to see all 3 columns — feeds, stories, and the story you selected.
> 
> Quit NewsBlur.
> 
> Open NewsBlur. Even though Column layout is set to 3, it acts like it’s set to 2. The feeds column disappears when you view a story. You have to reset the preference for it to work again.
