### ISSUE TITLE
iPad: Scroll performance on story titles

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1686]
Looks like the marking read on scroll action is what's causing a scrolling performance issue. See the video. It's smooth up top, so maybe we can queue up the read stories? That entire action has to be in a background thread, so is it the transition needing to draw a new state?

https://user-images.githubusercontent.com/44229/168652129-96108de1-5e5d-4103-a751-c63307540804.MOV

**Comment by Dejal** [comment]
I think this was due to the recent change to load thumbnail images while scrolling.

It was reloading the whole table when loading each image, which was unnecessary and has a performance penalty, so I've removed that. See if it's better now. (It's hard to tell on my iPad Pro, but seems faster.)

I don't think mark as read on scroll is relevant; you can easily check by turning that off.

If better for you, feel free to close this issue.

**Comment by Dejal** [comment]
Try this on for size. It now defers updating the feeds table, which should improve rapid scrolling performance, and avoid the highlight blinking. It also updates the header counts in the same way.

If good now, please close this issue.
