### ISSUE TITLE
iPhone: Don't allow double-tap to open original story while on story titles

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1751]
I somehow trigger a double-tap behavior on the story titles view while on iPhone. I do this all the time and have for years, so it's time to prevent it from happening. I can't reproduce it by double tapping fast, but if I do a certain type of scroll behavior and lightly brush the screen so i do inadvertently double-tap, I can make it happen. Anyway, I think the answer is to just prevent the action from happening on iPhone entirely, right?

**Comment by Dejal** [comment]
I could trigger it in the Simulator via a semi-long tap (not long enough to trigger the menu) then quick second tap. A little awkward, but I can see how it could be done accidentally.

Rather than remove this functionality, I have changed the default to do nothing, and changed the value so existing users will do nothing too. People who want this can re-enable the setting in the preferences. Fair enough?

**Comment by samuelclay** [comment]
I would like to change back to the default being to open the original story on iPad and for iPhone to do nothing no matter what.

**Comment by Dejal** [comment]
Okay, let's try this on for size.

- On iPhone, double-tapping in the feed detail does nothing.
- On iPad, double-tapping in the feed detail can show the original etc.
- On both, double-tapping is supported in the story view; defaults to open original story view.
