### ISSUE TITLE
iOS: Offline images aren't displaying

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1801]
They work in story previews, so I know they are there, but they are broken in stories and look like broken images. Only happening when in airplane mode.

**Comment by Dejal** [comment]
I don't think this is a critical issue, as it's how it's always been.

When drawing the story, it just displays the story content HTML, which includes `img` tags to the original site.

The preview in the Feed Detail does show a scaled (300x300) thumbnail from the image cache, which is why it works offline.

We could add logic to substitute the single thumbnail image into the story HTML, but it wouldn't have all of the images, and the scale may be a problem (would have to parse the image sizing to avoid that).

Alternatively, we could process the content HTML to strip out images when offline. Or substitute a placeholder image (which the broken image is kinda already doing).

Do you want me to try one of those approaches?

**Comment by samuelclay** [comment]
I don't understand, this used to work. The broken image is probably addressing the wrong offline stored image. Even if this has been the case, this is a critical issue and should be fixed in I believe the `dejal` branch so we can ship a fix out. I don't want to strip out images unless the user has Offline Images turned off. But if it's turned on, we should be showing them!

**Comment by Dejal** [comment]
Okay, I've figured out the issue. NewsBlur used to use `activeCachedImages` to substitute file URLs of cached images in the HTML, but that was removed by you on 2014-09-26 (before my time): `"Adding NSURLCache layer for caching of offline images. No more rewriting of image URLs."`

So the issue seems to be related to the change from `UIWebView` to `WKWebView` back in 2020. Since `WKWebView` uses an external iOS-controlled process to render pages, it isn't using the `NBURLCache`.

I'll see if I can make it either use the cache, or have a delegate handle it. If not, we could restore the old URL substitution code, perhaps only when offline.

**Comment by Dejal** [comment]
I spent some time trying to figure out if it is possible to use a custom cache or callback with `WKWebView`, but it doesn't seem like it is. Not too surprising, since it's in a separate process. So I restored the old image URL substitution approach, only used when offline, with some fixes to make it work. That seems a perfectly fine solution.
