### ISSUE TITLE
Android: Send story by email should include content

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1825]
A user wrote in that emailing stories through Android resulted in the story missing it's images. When I went to try it, the email was also missing it's content.

Here's the feed in question: https://www.newsblur.com/site/7614472/jesus-mo

**Comment by sictiru** [comment]
Since the content can be dynamic and could have multiple images, it's really not an option to share the content in a way that the images are going to be displayed embedded in the email. 

There were instances where the story's text wasn't available and the sharing logic wasn't checking for that properly due to a custom flag that was set in the database for these cases. This part was been updated to always include the story's content when shared via email.

**Comment by sictiru** [comment]
The fix mentioned above is live in v13.2.3
