### ISSUE TITLE
iOS: Infinite ad pop-up

### ISSUE THREAD

**Issue by adeftu** [samuelclay/NewsBlur#1909]
Some pages (eg Euronews) keep popping up an ad indefinitely with in-app browser, thus making reading it impossible. 

See below:
https://www.euronews.com/2024/11/06/kamala-harris-addresses-nation-after-conceding-election-to-donald-trump

https://github.com/user-attachments/assets/8640643e-16de-415d-be47-aae3b162cb68

iOS: 18.1
Newsblur: 13.1.1

**Comment by samuelclay** [comment]
I believe this is out of our hands. @Dejal can you confirm?

**Comment by Dejal** [comment]
Yes, if you're reading the story on the original site, they can show ads or other annoying behavior if they wish. Read the story in NewsBlur's normal story view to avoid that.

**Comment by adeftu** [comment]
What do you mean by “normal story view”?

Opening the same URL in Safari or Chrome doesn’t present this problem.

**Comment by samuelclay** [comment]
I'm just glad we're clearing the original in-app browser story view when leaving that window, otherwise those ads would keep playing. Anyway, this is due to the site. I suggest installing an ad blocker, which may not work in the in-app browser? I'm kind of surprised we still have this view. You should use the in-app Safari view, which is also an option under Preferences. It's a bit different, doesn't have our app skin, but extensions work and you can block those ads.
