### ISSUE TITLE
Backend: Use SNI when fetching feeds

### ISSUE THREAD

**Issue by Lukasa** [samuelclay/NewsBlur#534]
Mark Nottingham has switched his personal website over to require TLS SNI to access it, and [did a writeup of every client that failed to do so](https://www.mnot.net/blog/2014/05/09/if_you_can_read_this_youre_sniing). NewsBlur was one of them.

A quick dig through the codebase suggests that you're using requests for at least part of your feed fetching! Of course, we're delighted that you're using requests, and we'd like to help you avoid this problem.

Requests can transparently turn on SNI for you. On Python 2.X, you'll need to add the following packages to your list of dependencies: `PyOpenSSL`, `ndg-httpsclient` and `pyasn1`. This should also provide some security benefits, as we turn on a few nicer features and cipher suites when using PyOpenSSL.

This should be all you need to give you access to sites behind SNI. Let me know if you'd like me to help make this happen in any way: I'm a big fan of NewsBlur and use it a lot, so helping make it better would be awesome.

**Comment by samuelclay** [comment]
Still waiting on Ubuntu to support 2.7.9 without having to change apt sources.

**Comment by konklone** [comment]
@samuelclay That's unlikely to happen for Ubuntu 14.04. In the 9 months since finalizing 2.7.9, Ubuntu 14.04's Python 2 package had [one backport update in June for security fixes](http://changelogs.ubuntu.com/changelogs/pool/main/p/python2.7/python2.7_2.7.6-8ubuntu0.2/changelog), but that's it. 

[Ubuntu 15.04's Python 2 package](http://packages.ubuntu.com/source/vivid/python2.7) is based on Python 2.7.9. So if you did a dist-upgrade, this should come along with it.

**Comment by jdelic** [comment]
This is becoming a more and more pressing issue since Cloudflare is now deploying SNI and therefor feeds fronted through Cloudflare are becoming unavailable in NewsBlur. One particular example that impacts me and my paid account at newsblur.com is penny-arcade.com. Can we get an update on this, please?

**Comment by jdelic** [comment]
This is also related to the following thread on getsatisfaction.com: https://getsatisfaction.com/newsblur/topics/my-penny-arcade-feed-isnt-pulling-stories

**Comment by Lukasa** [comment]
To be clear, Ubuntu 14.04 *will not* get the backport of 2.7.9: see [here](https://bugs.launchpad.net/ubuntu/+source/python-defaults/+bug/1401322) for the discussion.

Assuming that all the deploys are working well, SNI should be functioning correctly here, so I'm a little intrigued as to why that's not working.

**Comment by jdelic** [comment]
I posted an OpenSSL command-line that I think shows the source of the error with penny-arcade.com on the above link to getsatisfaction. If the servers don't have Python 2.7.9, SLI support can be added to `requests` on Python 2.7.x by installing `pyOpenSSL`, `ndg-httpsclient` and `pyasn1`. Perhaps that helps? I haven't yet looked into NewsBlur's dependencies... they might be already in there.

**Comment by jdelic** [comment]
More detail on SLI support in requests here: https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

**Comment by Lukasa** [comment]
@jdelic They are: if you look through this thread you'll see that I added them in May 2014 as part of #536. That's why I want to know why it's not working.

**Comment by jdelic** [comment]
@Lukasa in that case I have only one alternative theory which is that PA/CloudFlare requires at least TLS 1.0 and iirc requests had problems with negotiating up from sslv3 on older Python versions? I vaguely remember having similar problems 2 years ago when we tried to move to TLS 1.2 at LaterPay. Quick testing with `openssl` shows that CloudFlare tries to at least negotiate `ECDHE-ECDSA-AES128-SHA` for TLSv1.

Unfortunately newsblur.com only provides very limited info on why reading the feed fails, but it shows up as "Untitled" and without content, which makes me think that NewsBlur is unable to read it at all. I currently have no box with an older Python version to test this from, but I might find some time tonight to set up a Vagrant VM and see if I can reproduce the error with NewsBlur's pinned versions. Since you seem to be familiar with the stack I think that you could test the feed URL from the getsatisfaction thread much faster than I could, though :)

**Comment by Lukasa** [comment]
As it happens I had an Ubuntu 14.04 machine floating around so I grabbed it and gave this a try. In a virtual environment running Python 2.7.6, with OpenSSL 1.0.1f, with the following requirements lifted directly from NewsBlur's requirements.txt (pruned to the set that are likely to be relevant):

```
requests==2.7.0
pyOpenSSL==0.14
pyasn1==0.1.7
ndg-httpsclient==0.3.2
simplejson==3.4.0
```

I had exactly no problem with the Penny Arcade feed URL in the linked thread. Status code 200 with an RSS feed in the response content. So whatever problem is being hit here it's unlikely to be related to SNI, unless the requirements.txt configuration is somehow not propagating into NewsBlur's environment.

**Comment by konklone** [comment]
FWIW, [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=penny-arcade.com&s=104.28.1.38&latest) does indicate that penny-arcade.com uses CloudFlare's free service and is only available via clients that support SNI.

**Comment by samuelclay** [comment]
NewsBlur uses `feedparser` to fetch feeds, which does not use `requests`. I could potentially switch the feed fetching to requests and then feeding that into feedparser, but that's a substantial change that I shouldn't have to make.

**Comment by Lukasa** [comment]
@samuelclay Ah, that explains that then!

So it seems like the options are either:

1. Someone undertakes to make a substantial PR to NewsBlur to change the feed fetching logic. Probably pretty painful for everyone involved.
2. Someone makes a PR to feedparser to change them away from urllib2.
3. NewsBlur updates to a newer LTS release, which will be Ubuntu 16.04 in a few months.

I have no horse in this race, NewsBlur is still working great for me!

**Comment by samuelclay** [comment]
We've upgraded (a while ago) and this should now be working.
