### ISSUE TITLE
Android: Story titles sometimes narrower than screen

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#589]
See screenshot: https://getsatisfaction.com/newsblur/topics/feed-list-view-compressed

![screenshot_2014-10-03-18-46-54_inline](https://cloud.githubusercontent.com/assets/44229/4510156/abbd45da-4b27-11e4-9223-f354771271ac.png)

**Comment by dosiecki** [comment]
Revisiting this, the root cause is that Android impl of a `TextView` with both the `ellipsize` and `maxlines` attributes is just incredibly buggy.  (see https://google.com/search?q=site%3Acode.google.com+textview+ellipsize+maxlines for just a sample of the mess)

It looks like later platform versions have made some attempts at improving things, and I certainly have never seen this in action on contemporary OS versions.  If anyone can reliably repro this on a 5.x device, we can reopen and consider whether to roll our own widget or change what we display.
