### ISSUE TITLE
Android: Use existing login session_id

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#671]
For some reason Android calls /reader/login every single time it loads. This is the wrong behavior. You should cache the newsblur_sessionid cookie on login and then reuse that overtime until it is invalid (and you get an 'authenticated: false' message in the response.

The reason for this necessary change is that all of those sessions are being stories in the database and it's causing the redis session database to become hugely bloated.

On iOS I don't have to do anything special, since the cookie is automatically stored and used on every newsblur.com request. This will also cut down some time when loading feeds, as the login call does not need to happen again. 

The cookie should be good for 1 year.

**Comment by dosiecki** [comment]
I can't find any evidence in logs that `/login` is being called after the login screen on either of my devices.  Did a cold lauch, a warm launch, a full sync, and a few reading actions and login was never called because the cookie was present and valid.

Do you have any additional info on what might be causing your device to forget the login cookie?  Is ther evidence on the server side to suggest that something is calling the API in way that is evading logging?

**Comment by samuelclay** [comment]
You're right, this behavior must've been fixed a while ago. Now I've gotta figure out why there are 25 million logins from the past year. Thanks!

**Comment by dosiecki** [comment]
Added some logging so it is easier to spot-check for this issue in the wild, even when debug logging is off.  Just in case it ever comes back up!
