### ISSUE TITLE
Respect site settings in "all site stories" view

### ISSUE THREAD

**Issue by Mosrite** [samuelclay/NewsBlur#687]
Hey,
I think it would be great if the per-site settings for the preferred view (feed, text, story) would be respected in the "all site stories" view as well. Could this be implemented as an option?
Thanks for considering my suggestion! :)

**Comment by samuelclay** [comment]
Yes, this has been suggested a few times. There's a thread on getsatisfaciton.com/newsblur about it. I designed it this way because you want to read different in a folder than you do in a feed. Switching views should be easy enough.

Also, some sites use the original view, which isn't available in Folder view. I would still entertain this, though. Just post on the forum.

**Comment by Mosrite** [comment]
Thanks, I'll watch the respective thread on getsatisfaction.com.
