### ISSUE TITLE
[Feature Request] Twitter fetcher (like the one for Youtube)

### ISSUE THREAD

**Issue by Mosrite** [samuelclay/NewsBlur#688]
I think it's awesome that NewsBlur features its own Youtube->Feed converter now! Maybe, something similar could be built for Twitter? So that users could add Twitter accounts as RSS feeds? I know that Twitter stopped supporting RSS a while ago, but maybe a similar solution like for Youtube can be found?
Thanks in advance for considering my suggestion!

**Comment by samuelclay** [comment]
I would love to do this but there's no way Twitter will allow it. They cap their API so low that I wouldn't be able to fetch much at all, since I'd be sharing the same twitter api key for all user's subscribed sites.

**Comment by Mosrite** [comment]
Services like feed43.com can build RSS feeds from basically any other site. I'm not a programmer, so I have no idea how this is done. I assumed you built something similar, just specifically for Youtube. But if I understand you correctly now, I was wrong and your new feature is still built around YT's API, right? I see that this is not possible for Twitter.
Thanks for answering, though! :)

**Comment by samuelclay** [comment]
Yes, the new YouTube fetcher is built around its API. Google helpfully provides a dashboard for how close I am to hitting their payment quota. I'm about half-way there, but I don't see that rising all too much, and if it does I can just scale back YouTube fetches. Right now I'm doing 2 requests per second, every second of the day, just to handle the 63,928 youtube feeds with 81,456 subscribers.

Twitter's numbers are similar, with 71,761 twitter feeds, but the subscriber numbers are higher at 100,913 people. So that's just not going to cut it with regards to their API, which pretty much limits you to 15 calls every 15 minutes. Not gonna happen.

**Comment by samuelclay** [comment]
SELECT sum(num_subscribers) FROM feeds WHERE feed_address LIKE '%youtube.com%'

**Comment by samuelclay** [comment]
Had that in my clipboard and figured it was relevant.

**Comment by samuelclay** [comment]
And here's Twitter developer-hostile rate limits: https://dev.twitter.com/rest/public/rate-limiting
