### ISSUE TITLE
Android: v4.3.0 authentication no longer works

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#708]
While this is not a huge deal, as it only effects those who have to re-login because their auth cookies last exactly a year, the end of June is a busy renewal time. So I'm getting a few reports of users not being able to login on v4.3.0. And as we've seen with login_as, there's something fishy going on with redirects.

**Comment by samuelclay** [comment]
From a user: "The error = wrong password". It's a memorized password, so chances are it's the correct password.

**Comment by samuelclay** [comment]
This is addressed in #707.

**Comment by dosiecki** [comment]
I'm not certain #707 would have fixed this fully.

What exactly happens when the cookie expires?  As I understood it, the `/reader/feeds` API returns a 200 response with the `authenticated` member set to `false`.  That that point, we stop, clear the cookie and prompt the user to login once more, as if they had just installed.  No redirects involved.  That is the entirety of our handling for it.  Are we missing something?

**Comment by samuelclay** [comment]
Oh no, I messed up. Turns out having the user change passwords fixed it.
