### ISSUE TITLE
Android: Fatal API Failures May Block Updates

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#713]
We've had several reports over the last few days of Android users being unable to get new stories on their devices.  After working with some affected users, it appears that some API action(s) are getting stuck in the action queue, blocking further API activity.

As a general rule, pending API actions (mark read, save, share, etc) are executed ASAP before other API actions or reads.  If these fail for any unexpected reason, they are kept in the queue to prevent data loss.  To ensure correct order-of-operations, they are executed strictly in the order corresponding to the user actions that caused them.  Should any API action fail repeatedly or in a fatal manner, that action can block the API queue and cause the app to stop functioning properly.

I haven't been able to reproduce any of these fatal API calls, so it is difficult to diagnose what is causing them.  If anyone can identify one or more, we can put together a fix.  There appears to have been a spike in these over the last few days, if that leads to any hints.

As a work-around, the action queue can be cleared by logging out/in of the app.

**Comment by samuelclay** [comment]
I don't have this queue on iOS. If anything fails, it either informs the user with a toast (story failed to save/share/mark unread/delete/rename/train), or silently fails (mark read is the only one I can think of).

We can probably toss this queue or execute it out of order. It's not really that important to get the order 100% correct, since most of the time it's read this, save that. 

I'd reconsider the queue and just get rid of it. Retry a call once and then don't bother.

**Comment by dosiecki** [comment]
Wait, then how does offline work in iOS?  I would hate to lose all my reads / saves / shares when I am reading on the subway.

**Comment by samuelclay** [comment]
iOS doesn't actually check whether it's offline or not. If a mark read fails, it gets added to a db table. When you refresh your feeds (whether by pulling to refresh or automatically after re-entering the app after 10 minutes since last refresh action), that table gets cleared and sent to mark_story_hashes_as_read. If that fails, they are added back into the table. (It may just clear them on success, but that's not a big difference).

**Comment by samuelclay** [comment]
Can't share or save while offline on iOS. But saving would work the same way.

**Comment by dosiecki** [comment]
Ah, okay, that is functionally what the Android app does, though it also happens to perform everything in order and stop if anything fails.  I'll make it so that things keep getting executed even if a call fails. (they are aggressively logged, so if we do ever figure it out, we can still diagnose)

Are there no edge cases where order matters?  Like, would it be a terrible failure to try and mark-read a feed after having unsubscribed to it?

**Comment by samuelclay** [comment]
Nope, marking read after unsubscribing would be fine. You might get a message saying you're unsubscribed, but it's not a big deal.

**Comment by dosiecki** [comment]
So, though this is fixed for the next release, it would be nice to understand why, in the last week, some calls are now failing no mater how many retries we perform.

Is it possible to dive into logs and discover what is going on?  The app probably needs to understand the criteria for eventually discarding these poison pills, or else it will burn a ton of resources attempting to retry them over and over.

**Comment by samuelclay** [comment]
Only retry broken calls once. Toss them after that.

**Comment by dosiecki** [comment]
Fixed in #717.
