### ISSUE TITLE
Android: View Mode Naming is Inconsistent with Web

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#749]
Ran afoul of this while helping a user today and can't beleive I never noticed this before: the Android app uses different nomenclature for story view modes than the Web does.

    (web view mode name) -> (Android view mode name)
    Feed  ->  Story
    Text  ->  Text
    Story ->  n/a

How should we got about making these consistent without deeply confusing users who are familiar with the existing naming?

**Comment by samuelclay** [comment]
Change it and don't worry about users who have to adjust. Happens all the time. If we switch to a better system, they'll get used to it very quickly.

Also, where does it say this? Feed/Story?

**Comment by samuelclay** [comment]
I'm assuming this isn't the Story/Text button in the bottom left of the story detail view, which seems correct.

**Comment by dosiecki** [comment]
It incorrectly says "Story" view mode  where it means "Feed" view mode in at least two places:

* the overlay button that lets you switch into "Text" view mode incorrectly says "Story" when it actually switches you back to "Feed" view mode
* the preferences for default view mode incorrectly say "Story" when they actually default feeds to "Feed" view mode

**Comment by samuelclay** [comment]
Ah-ha, that inconsistency is on iOS as well. I think it's better to say Story/Text instead of Feed/Text. If you've noticed, I dislike the word Feed, esp. when it relates to anything other than the RSS feed itself. So I use Story here, and Original Story is the Story view on iOS, believe it or not. So we conflate those terms quite a bit. I think it's fine to leave it as Story/Text for the overlay and for the preference, even if it doesn't match the web.

**Comment by dosiecki** [comment]
Should we leave this open to capture that mismatch in case we want to address it in the future?

**Comment by samuelclay** [comment]
Yeah, if it's only the overlay and in Prefs (which refer to the overlay), then this ticket is no longer needed.
