### ISSUE TITLE
iOS: Story navigation buttons on bottom of story detail are mis-aligned on first load

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#772]
![image2](https://cloud.githubusercontent.com/assets/44229/10594301/98ab3918-7680-11e5-91d2-36b54953f2c2.png)
![image3](https://cloud.githubusercontent.com/assets/44229/10594303/9d742d6a-7680-11e5-9a35-b46189cebb59.png)

**Comment by samuelclay** [comment]
I'd like to fix this bug next, since it's the only bug I actually see regularly.

**Comment by Dejal** [comment]
Yes, I see it too.  I actually already spent some time tracing it, but couldn't figure out the cause, so put it aside for now.  My notes, in case this makes the cause obvious to you:

- Traced to StoryDetailViewController -drawStory:withOrientation: on the [self.webView loadHTMLString:htmlString baseURL:baseURL]; line.  Doesn't occur when that is commented out.
- Seems like an auto layout constraint issue.  There's a constraint from the traverseView to the bottomSize view, which may be affected.
- Looks like the web view is sized too large, going behind the split bar at the bottom (scrolling reveals it extends behind the bar).
- Could hack it by adjusting the constraint or forcing layout or something after loading the HTML, but it'd probably still move around.

I'll take another look shortly.

**Comment by samuelclay** [comment]
So I just migrated that story traversal buttons (what those 4 buttons are called) to auto layout while fixing some other bugs. You'll notice, and quickly I'd imagine, that this is the worst code of the entire app. Getting stories to layout, with rotations, is a PITA. 

Want to see an awful bug? Go into a story, back out, rotate the device, go back into the story. Figure that one out and I think some other bugs will present themselves in place of any fix. It's entirely because of the way StoryPageController operates with a buffered list of three moving pages. And we can't lose scroll position or redraw the story after rotation, since videos might be playing and we don't want to lose that.

**Comment by Dejal** [comment]
Yeah, I had a quick play; I could get it to adjust to the right width by adding -resetPages and -refreshPages in StoryPageControl’s -viewWillAppear:, but that had other issues.  Something like that would likely be the solution, though.

I've investigated the traversal buttons issue.  It turns out that sometimes (particularly on first load) the StoryDetailController's view is too tall.  For example, when the page view is 672 high, the detail view is 684, which makes the enclosed web view 684, thus extending below the visible area, and thus pulling down the buttons.

I can adjust the height easily enough, though that leaves a gray bar above the web view.  Still an improvement, as the traversal buttons are then correct, but not perfect.  Probably need to tweak something else (offsetting the y position doesn't help, though).

I'll play some more tomorrow, unless that's good enough.

![simulator screen shot 2015-10-23 22 19 47](https://cloud.githubusercontent.com/assets/1318849/10709026/35c0c8fc-79d4-11e5-9a91-0bc8dac6bb1f.png)

**Comment by samuelclay** [comment]
So that grey bar is the reason that the height is being distorted. By why only on the first load? Anyway, we can't leave that grey bar in, because I purposefully squashed that space for the feed color bar.

Try reading by folder instead and you should see that bar get even taller.
