### ISSUE TITLE
iOS: Can't exit video from Safari View Controller

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#776]
"When I open a full screen video from the safari in app browser, I cannot tap the done button and leave the video. Have to force quit the app. Either rotation positions have this problem. "

**Comment by Dejal** [comment]
I can't reproduce this one.  The Done button is always available when expected.  I don't know how it could fail to work, as the Safari View Controller takes over the UI while displayed.

Possible they are referring to the Done button of the Safari View Controller instead of the full-screen video, and don't realize they have to scroll to the top to reveal it?
