### ISSUE TITLE
iOS: Custom domain

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#813]
The bottom preference in settings. "Custom domain" is allowing a user to use their own hosted install.

**Comment by Dejal** [comment]
Want this for 5.1 or 5.2?

I assume that you want a "Custom domain" setting added, and all uses of the `www.newsblur.com` domain to use the custom one if set.  

What about `ios.newsblur.com` and `s3.amazonaws.com/icons.newsblur.com`?  Should there be fields for those too, or always use those domains instead of custom (if that'd even work), or something else?

**Comment by samuelclay** [comment]
We can punt on this for a bit. As for ios.newsblur.com, that's just a hack to recognize the tap events in uiwebviews. And if the user has a custom domain, switch to the www.custom_domain.com/rss_feeds/icon/FEED_ID url.

**Comment by Dejal** [comment]
This is complete, so I'll close it.
