### ISSUE TITLE
Android: Add Saved Stories segmented control to All/Unread/Focus

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#898]
Saved stories by feed, showing the saved count per feed in blue (same as the unread counts for saved stories). This exists on the web.

Adding `read_filter=starred` will get you the stories, per-feed. 

The counts are in `starred_counts` from /reader/feeds?flat=true. It is two parts merged:

```
...
{
    "count": 1,
    "feed_address": null,
    "feed_id": 5077457,
    "tag": null
},
{
    "count": 1,
    "feed_address": null,
    "feed_id": 97100,
    "tag": null
},
{
    "count": 5,
    "feed_address": "http://www.newsblur.com/reader/starred_rss/13/db0d7a788724/art",
    "feed_id": null,
    "tag": "Art"
},
{
    "count": 3,
    "feed_address": "http://www.newsblur.com/reader/starred_rss/13/db0d7a788724/",
    "feed_id": null,
    "tag": "being human"
},
...
```

The top two are the feed counts, bottom two are the tag counts. Why I merged the two I don't know but it's easy to separate them.

**Comment by dosiecki** [comment]
Hmm, this way of looking at saved stories by feed is a bit different than how I had the design in my head and how I was already coding things.  I had thus far been treating saved counts for a feed as a sort of specialised tag and showing both tags and feed groupings in the expandable tree under the all-saved-stories list item.

This made sense to me, in that it puts all of the saved stories info in one spot in the UI, lets you see saved counts by feed, and avoids the myriad evils of a modal filter UI.

Would you be willing to entertain a demo version of the UI that works in this way? I am liking the design for my own use, and it is virtually finished, once I merge this code that I started a month ago with all of the hyperuser rewrites that pushed it back.

**Comment by samuelclay** [comment]
Sure I'll take a look, but why not merge the two and let feeds show their own saved story count?

**Comment by dosiecki** [comment]
*(Bias Disclaimer: I find modal interfaces deeply confusing for users and Android has a really bad history with them; users often end up saying "my stories/emails/photos are missing!" when in reality they were just in the wrong mode.)*

Just my personal thought process that led me to the particular UI choice?  It never even dawned on me to make saved viewing a mode rather than a heirarchy.  Since saved stories as split by tags were viewed as a level under the existing saved stories section of the tree, saved stories split by feed also belonged there at that level.  Furthermore, I think of saved stories as having been archived and thus behave differently than fresh stories (no read state, no intel state, ordered by save date rather than publish date, etc), they live in a separate world down in the lower part of the tree.

I would also find the use of a mode switch a bit confusing because some saved story sections already do appear (and always have appeared) when not in a 'saved' mode, so why should slicing and dicing in this one new way require a mode switch?  

All that said, moving to the design as described in this issue wouldn't be too enormous a change, code-wise.

**Comment by samuelclay** [comment]
I hear you. It's a tradeoff between consistency (lists of lists) and ease (list modes). Since we already have the mode "problem" where users get into Focus mode or Text mode and don't understand why they are there, it seems to me that we've already solved it with messaging. Show the "No saved stories" dialog if nothing, just like we do for Focus. And if they do have a saved story, the user taps the feed, sees that the story has a clock next to its title (web and iOS do this, does android change the story title when a story is saved? that should definitely be a ticket if not), and realizes it's a saved story.

**Comment by samuelclay** [comment]
Can we use the updated icons from iOS? Check clients/ios/Resource/unread_yellow@3x.png, unread_green, and unread_blue. Oh, and all@3x.png. 

https://github.com/samuelclay/NewsBlur/blob/5.1/clients/ios/Resources/unread_blue%403x.png
https://github.com/samuelclay/NewsBlur/blob/5.1/clients/ios/Resources/unread_green%403x.png
https://github.com/samuelclay/NewsBlur/blob/5.1/clients/ios/Resources/unread_yellow%403x.png
https://github.com/samuelclay/NewsBlur/blob/5.1/clients/ios/Resources/all%403x.png

**Comment by samuelclay** [comment]
Note that they are only in the 5.1 branch right now. But feel free to just copy those resources over.

**Comment by dosiecki** [comment]
Absolutely. My first PR will be just the new functionality, and then I am
going to do a big UI pass to get things up to date and consistent in
several spots.

**Comment by dosiecki** [comment]
done in #902
