### ISSUE TITLE
iOS: Forgot Password flow

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#899]
Just open a web view with: http://www.newsblur.com/folder_rss/forgot_password

**Comment by Dejal** [comment]
Done.  Like the website, it shows the Forgot? button after an error (styled to fit in the iPhone and iPad UI).  Since it's obviously a web page, I used a Safari View Controller.  A more native approach would be a custom view with a field and Cancel/Send buttons, that does a POST to the form address, but perhaps not worth it for this.

**Comment by Dejal** [comment]
Not sure of the status of this issue; it seems like it was done, but the label were changed after my commit?

**Comment by Dejal** [comment]
Do you want to keep this open with the idea of doing a custom native view for forgot password at some point?  Or should we close it as good enough with the current web-based implementation?

**Comment by samuelclay** [comment]
I think sending to the web is a fine solution.
