### ISSUE TITLE
iOS: Move to iOS standard pull-to-refresh

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#945]
The old pull to refresh is broken on iOS 10.

**Comment by samuelclay** [comment]
Hey David, any chance we could get this in this week? iOS 10 drops today and I'd love to get this one fixed.

**Comment by Dejal** [comment]
Yes, since it's urgent I should be able to do that today.

**Comment by samuelclay** [comment]
Sweet, thanks for the prompt fix!

**Comment by nriley** [comment]
This is still somewhat broken; the behavior of the pull-to-refresh is not standard as the spinner disappears immediately instead of sticking around until the refresh completes, which makes me wonder if it worked (I'm not used to looking down at the bottom of the screen to see progress).  It's really in the uncanny valley of UI for me and has been infuriating to use.  I may or may not get to this myself, but if anyone else has a chance I'd appreciate it...

**Comment by samuelclay** [comment]
Yeah, I noticed that too. I think it should disappear once the "On its way..." is finished (like it used to).

**Comment by Dejal** [comment]
Do you want me to have a go at fixing it?

**Comment by nriley** [comment]
Please. I'm crazy overloaded with life right now.
