### ISSUE TITLE
self-hosted documentation

### ISSUE THREAD

**Issue by creactiviti** [samuelclay/NewsBlur#946]
I'm racking my brains for a couple of days trying to get NewsBlur installed on a local VM and had failed miserably so far. 

Any way we can get a step-by-step installation guide?

**Comment by jrottenberg** [comment]
You should use docker installation, it's pretty straightforward with docker-compose.

**Comment by creactiviti** [comment]
thank you @jrottenberg. I'm running into issues with that as well though. I think that would work great for the application itself but not for the persistent pieces (i.e. Postgres/MySQL, Redis etc.)

**Comment by samuelclay** [comment]
Just waiting on #947 to fix some formatting and we'll have that merged in.

**Comment by remram44** [comment]
I just started NewsBlur via docker-compose, however I'm noticing that feeds update really slowly (one feed every couple minutes... so 3 hours to fetch 100 feeds). Moreover clicking on "insta-fetch" shows a rate-limited message.

Is there a way to tweak the refresh delay/rate limit somewhere? Am I hitting another bug?

**Comment by samuelclay** [comment]
So the fetching that's happening there is when the client sees that feeds aren't being updated and updates them itself (on the app servers). It essential,lly Insta-fetches the feeds since they aren't being updated in the background.

You need to run the celery workers. I would just have them run every single queue and not split them up. If you omit the queue name, celery will just handle them all.

You also need to setup celery's celery beat, which performs scheduled tasks. Those tasks are what fill the feed queue and then send the stale feeds out to the task queues.

**Comment by Lich4r** [comment]
Hi,

How did you manage to install newsblur with docker ?

I've read the docker installation but I guess I'm missing something.
