### ISSUE TITLE
Sort "newsletters" by list-id

### ISSUE THREAD

**Issue by yardenac** [samuelclay/NewsBlur#961]
Sorting simple newsletters by their "From" header makes sense, but mailing lists with multiple senders should be sorted by their list-id header. For example, if I subscribe newsblur to the [linux kernel mailing list](http://vger.kernel.org/vger-lists.html#linux-kernel), the incoming mails will look like this:

From: Linus Torvalds torvalds@linux-foundation.org
List-ID: <linux-kernel.vger.kernel.org>

As it stands now, I would see a new folder called "Linus Torvalds", and thousands more folders for everybody else who sends to the list. But if you sorted by the list-id header when it exists, I would only see one folder for the whole list. This would be much more useful!

**Comment by samuelclay** [comment]
Problem with List-ID is that there is no friendly feed name like there is with the sender name. It's also a bit too late to change this, since there are thousands of mailing list feeds that are based off the sender email and not the List-ID. 

I'd be happy to reconsider but I would like to see some evidence that this would result in a better experience for everybody.
