### ISSUE TITLE
Automatic Installer

### ISSUE THREAD

**Issue by royalterra** [samuelclay/NewsBlur#971]
I believe I have the seam troubles of many others I install all dependence I try to build this at the end is not system to make works.

I try with 3 new installation in debian and is a waste of time I believe is more a question of Luck . I see anyway this project is propose in Bitnami . Binami is not my real idea for a working system  but can solve the problem temporally  . But in Binami there are't in off Votes Please to any one Vote here [Bitnami New Blur](https://bitnami.com/stack/newsblur)  and promote the project .

Anyway is there in any place a script auto installer?

**Comment by samuelclay** [comment]
I suggest using Docker. Alternatively, if you run this in an Ubuntu VM, you can re-use the fabric script and other commands detailed in the README.

NewsBlur has a ton of dependencies since it relies on a bunch of different databases. It's the nature of the beast, since NB does so many different things. But the web server is entirely under a python virtualenv, so those dependencies should be trivial to `pip install -r requirements.txt`. And you can get the four databases running on your own. Apart from that, getting them hooked up takes a bit of elbow grease.
