### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [samuelclay/NewsBlur#975]
When I perform this sequence of events, the scroll view on screen goes back to the top

Sequence 1
1. Click on Preferences
2. Scroll Down
3. Orientation Change

Sequence 2
1. Click on Read Stories
2. Click on Story item in list
3. Scroll Down
4. Orientation Change

**Comment by dosiecki** [comment]
This is a well-known issue in Android.  In all cases but one, the preservation of fragment scroll state is fully delegated to the platform.  Whether or not state is preserved is dictated by a good number of factors including your device firmware and available resources.  The one exception to this is a known bug with preservation of scroll state while reading stories due to an upstream bug in the Android support libraries.  This is being tracked in #199.
