### ISSUE TITLE
Android: app keeps losing settings

### ISSUE THREAD

**Issue by stsquad** [samuelclay/NewsBlur#985]
I track the NewsBlur app via f-droid but of late I find it often loses all my settings after an update. Not only do credentials need to be re-entered but all the preferences get lost (read order, default filter, theme etc).

I've not been able to trigger this on demand but I suspect app updates might be the cause.

**Comment by dosiecki** [comment]
The recent incidence of this is related to a server-side bug around cookie brownouts, and should be eventually fixed.  The Android app has meanwhile been updated with a workaround that tolerates temporary cookie loss without settings loss in HEAD, but due to the way F-Droid triggers auto builds, you might not yet have it.  For the moment, you can do a source build from github or grab the beta from the Play Store, or wait for us to cut a new version flag, after which all future F-Droid builds will have the workaround.

**Comment by dosiecki** [comment]
Any build from 74462d91619cd6877e3b1345feadb67e98d7b0cb onward should be good.

**Comment by samuelclay** [comment]
Ok, I'm going to push this build out as v5.0.0. Remind me again what are the features included apart from what's already here:

Version 5.0.0 (November 2016)
 * New gesture to mark a story as read and unread by swiping on the story title
 * UI updates to story titles
 * New preferences for changing the font size of feed titles and story titles
 * Fleuron on the bottom of story lists better help you keep tracking of where you are in a feed.

**Comment by dosiecki** [comment]
* Thumbnails in story lists
* Forgot-password workflow
* Much higher-resolution icons throughout
* Feed muting/unmuting
* Option to enable confirmation for destructive mark-reads
* Custom server support
